// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain-index/index.proto

package com.bibox.dex.proto.index;

public final class IndexProto {
  private IndexProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code chainindex.api.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *普通地址产生的交易事件
     * </pre>
     *
     * <code>EV_TX = 0;</code>
     */
    EV_TX(0),
    /**
     * <pre>
     *合约产生的action事件
     * </pre>
     *
     * <code>EV_ACT = 1;</code>
     */
    EV_ACT(1),
    /**
     * <pre>
     *心跳事件
     * </pre>
     *
     * <code>EV_HB = 998;</code>
     */
    EV_HB(998),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *普通地址产生的交易事件
     * </pre>
     *
     * <code>EV_TX = 0;</code>
     */
    public static final int EV_TX_VALUE = 0;
    /**
     * <pre>
     *合约产生的action事件
     * </pre>
     *
     * <code>EV_ACT = 1;</code>
     */
    public static final int EV_ACT_VALUE = 1;
    /**
     * <pre>
     *心跳事件
     * </pre>
     *
     * <code>EV_HB = 998;</code>
     */
    public static final int EV_HB_VALUE = 998;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return EV_TX;
        case 1: return EV_ACT;
        case 998: return EV_HB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bibox.dex.proto.index.IndexProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:chainindex.api.EventType)
  }

  public interface SubscribeEventRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:chainindex.api.SubscribeEventRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.shared.api.ChainType chain = 1;</code>
     */
    int getChainValue();
    /**
     * <code>.shared.api.ChainType chain = 1;</code>
     */
    com.bibox.dex.proto.shared.TokenProto.ChainType getChain();

    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    java.util.List<java.lang.String>
        getAddresssList();
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    int getAddresssCount();
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    java.lang.String getAddresss(int index);
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddresssBytes(int index);

    /**
     * <pre>
     *事件的起始block，用来查询历史，-1 表示不用此条件
     * </pre>
     *
     * <code>int64 block_num_start = 3;</code>
     */
    long getBlockNumStart();

    /**
     * <pre>
     *事件的起始时间，用来查询历史，-1表示不用此条件
     * </pre>
     *
     * <code>int64 block_time_start = 4;</code>
     */
    long getBlockTimeStart();

    /**
     * <pre>
     *订阅事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 5;</code>
     */
    int getEventValue();
    /**
     * <pre>
     *订阅事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 5;</code>
     */
    com.bibox.dex.proto.index.IndexProto.EventType getEvent();
  }
  /**
   * Protobuf type {@code chainindex.api.SubscribeEventRequest}
   */
  public  static final class SubscribeEventRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:chainindex.api.SubscribeEventRequest)
      SubscribeEventRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeEventRequest.newBuilder() to construct.
    private SubscribeEventRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeEventRequest() {
      chain_ = 0;
      addresss_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      blockNumStart_ = 0L;
      blockTimeStart_ = 0L;
      event_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubscribeEventRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              chain_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addresss_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              addresss_.add(s);
              break;
            }
            case 24: {

              blockNumStart_ = input.readInt64();
              break;
            }
            case 32: {

              blockTimeStart_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addresss_ = addresss_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.class, com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CHAIN_FIELD_NUMBER = 1;
    private int chain_;
    /**
     * <code>.shared.api.ChainType chain = 1;</code>
     */
    public int getChainValue() {
      return chain_;
    }
    /**
     * <code>.shared.api.ChainType chain = 1;</code>
     */
    public com.bibox.dex.proto.shared.TokenProto.ChainType getChain() {
      com.bibox.dex.proto.shared.TokenProto.ChainType result = com.bibox.dex.proto.shared.TokenProto.ChainType.valueOf(chain_);
      return result == null ? com.bibox.dex.proto.shared.TokenProto.ChainType.UNRECOGNIZED : result;
    }

    public static final int ADDRESSS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList addresss_;
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddresssList() {
      return addresss_;
    }
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    public int getAddresssCount() {
      return addresss_.size();
    }
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    public java.lang.String getAddresss(int index) {
      return addresss_.get(index);
    }
    /**
     * <pre>
     *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
     * </pre>
     *
     * <code>repeated string addresss = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddresssBytes(int index) {
      return addresss_.getByteString(index);
    }

    public static final int BLOCK_NUM_START_FIELD_NUMBER = 3;
    private long blockNumStart_;
    /**
     * <pre>
     *事件的起始block，用来查询历史，-1 表示不用此条件
     * </pre>
     *
     * <code>int64 block_num_start = 3;</code>
     */
    public long getBlockNumStart() {
      return blockNumStart_;
    }

    public static final int BLOCK_TIME_START_FIELD_NUMBER = 4;
    private long blockTimeStart_;
    /**
     * <pre>
     *事件的起始时间，用来查询历史，-1表示不用此条件
     * </pre>
     *
     * <code>int64 block_time_start = 4;</code>
     */
    public long getBlockTimeStart() {
      return blockTimeStart_;
    }

    public static final int EVENT_FIELD_NUMBER = 5;
    private int event_;
    /**
     * <pre>
     *订阅事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 5;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <pre>
     *订阅事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 5;</code>
     */
    public com.bibox.dex.proto.index.IndexProto.EventType getEvent() {
      com.bibox.dex.proto.index.IndexProto.EventType result = com.bibox.dex.proto.index.IndexProto.EventType.valueOf(event_);
      return result == null ? com.bibox.dex.proto.index.IndexProto.EventType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chain_ != com.bibox.dex.proto.shared.TokenProto.ChainType.CHAIN_UNKNOWN.getNumber()) {
        output.writeEnum(1, chain_);
      }
      for (int i = 0; i < addresss_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addresss_.getRaw(i));
      }
      if (blockNumStart_ != 0L) {
        output.writeInt64(3, blockNumStart_);
      }
      if (blockTimeStart_ != 0L) {
        output.writeInt64(4, blockTimeStart_);
      }
      if (event_ != com.bibox.dex.proto.index.IndexProto.EventType.EV_TX.getNumber()) {
        output.writeEnum(5, event_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chain_ != com.bibox.dex.proto.shared.TokenProto.ChainType.CHAIN_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, chain_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addresss_.size(); i++) {
          dataSize += computeStringSizeNoTag(addresss_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddresssList().size();
      }
      if (blockNumStart_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, blockNumStart_);
      }
      if (blockTimeStart_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, blockTimeStart_);
      }
      if (event_ != com.bibox.dex.proto.index.IndexProto.EventType.EV_TX.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, event_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest)) {
        return super.equals(obj);
      }
      com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest other = (com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest) obj;

      boolean result = true;
      result = result && chain_ == other.chain_;
      result = result && getAddresssList()
          .equals(other.getAddresssList());
      result = result && (getBlockNumStart()
          == other.getBlockNumStart());
      result = result && (getBlockTimeStart()
          == other.getBlockTimeStart());
      result = result && event_ == other.event_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAIN_FIELD_NUMBER;
      hash = (53 * hash) + chain_;
      if (getAddresssCount() > 0) {
        hash = (37 * hash) + ADDRESSS_FIELD_NUMBER;
        hash = (53 * hash) + getAddresssList().hashCode();
      }
      hash = (37 * hash) + BLOCK_NUM_START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockNumStart());
      hash = (37 * hash) + BLOCK_TIME_START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockTimeStart());
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chainindex.api.SubscribeEventRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:chainindex.api.SubscribeEventRequest)
        com.bibox.dex.proto.index.IndexProto.SubscribeEventRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.class, com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.Builder.class);
      }

      // Construct using com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chain_ = 0;

        addresss_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        blockNumStart_ = 0L;

        blockTimeStart_ = 0L;

        event_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventRequest_descriptor;
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest getDefaultInstanceForType() {
        return com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.getDefaultInstance();
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest build() {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest buildPartial() {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest result = new com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.chain_ = chain_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          addresss_ = addresss_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.addresss_ = addresss_;
        result.blockNumStart_ = blockNumStart_;
        result.blockTimeStart_ = blockTimeStart_;
        result.event_ = event_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest) {
          return mergeFrom((com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest other) {
        if (other == com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest.getDefaultInstance()) return this;
        if (other.chain_ != 0) {
          setChainValue(other.getChainValue());
        }
        if (!other.addresss_.isEmpty()) {
          if (addresss_.isEmpty()) {
            addresss_ = other.addresss_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAddresssIsMutable();
            addresss_.addAll(other.addresss_);
          }
          onChanged();
        }
        if (other.getBlockNumStart() != 0L) {
          setBlockNumStart(other.getBlockNumStart());
        }
        if (other.getBlockTimeStart() != 0L) {
          setBlockTimeStart(other.getBlockTimeStart());
        }
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int chain_ = 0;
      /**
       * <code>.shared.api.ChainType chain = 1;</code>
       */
      public int getChainValue() {
        return chain_;
      }
      /**
       * <code>.shared.api.ChainType chain = 1;</code>
       */
      public Builder setChainValue(int value) {
        chain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.shared.api.ChainType chain = 1;</code>
       */
      public com.bibox.dex.proto.shared.TokenProto.ChainType getChain() {
        com.bibox.dex.proto.shared.TokenProto.ChainType result = com.bibox.dex.proto.shared.TokenProto.ChainType.valueOf(chain_);
        return result == null ? com.bibox.dex.proto.shared.TokenProto.ChainType.UNRECOGNIZED : result;
      }
      /**
       * <code>.shared.api.ChainType chain = 1;</code>
       */
      public Builder setChain(com.bibox.dex.proto.shared.TokenProto.ChainType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chain_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.shared.api.ChainType chain = 1;</code>
       */
      public Builder clearChain() {
        
        chain_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList addresss_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddresssIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addresss_ = new com.google.protobuf.LazyStringArrayList(addresss_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddresssList() {
        return addresss_.getUnmodifiableView();
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public int getAddresssCount() {
        return addresss_.size();
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public java.lang.String getAddresss(int index) {
        return addresss_.get(index);
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddresssBytes(int index) {
        return addresss_.getByteString(index);
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public Builder setAddresss(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddresssIsMutable();
        addresss_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public Builder addAddresss(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddresssIsMutable();
        addresss_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public Builder addAllAddresss(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddresssIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addresss_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public Builder clearAddresss() {
        addresss_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指定地址,若为空则用数据库里的地址（每个BF钱包地址都会进入数据库）
       * </pre>
       *
       * <code>repeated string addresss = 2;</code>
       */
      public Builder addAddresssBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddresssIsMutable();
        addresss_.add(value);
        onChanged();
        return this;
      }

      private long blockNumStart_ ;
      /**
       * <pre>
       *事件的起始block，用来查询历史，-1 表示不用此条件
       * </pre>
       *
       * <code>int64 block_num_start = 3;</code>
       */
      public long getBlockNumStart() {
        return blockNumStart_;
      }
      /**
       * <pre>
       *事件的起始block，用来查询历史，-1 表示不用此条件
       * </pre>
       *
       * <code>int64 block_num_start = 3;</code>
       */
      public Builder setBlockNumStart(long value) {
        
        blockNumStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件的起始block，用来查询历史，-1 表示不用此条件
       * </pre>
       *
       * <code>int64 block_num_start = 3;</code>
       */
      public Builder clearBlockNumStart() {
        
        blockNumStart_ = 0L;
        onChanged();
        return this;
      }

      private long blockTimeStart_ ;
      /**
       * <pre>
       *事件的起始时间，用来查询历史，-1表示不用此条件
       * </pre>
       *
       * <code>int64 block_time_start = 4;</code>
       */
      public long getBlockTimeStart() {
        return blockTimeStart_;
      }
      /**
       * <pre>
       *事件的起始时间，用来查询历史，-1表示不用此条件
       * </pre>
       *
       * <code>int64 block_time_start = 4;</code>
       */
      public Builder setBlockTimeStart(long value) {
        
        blockTimeStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件的起始时间，用来查询历史，-1表示不用此条件
       * </pre>
       *
       * <code>int64 block_time_start = 4;</code>
       */
      public Builder clearBlockTimeStart() {
        
        blockTimeStart_ = 0L;
        onChanged();
        return this;
      }

      private int event_ = 0;
      /**
       * <pre>
       *订阅事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 5;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <pre>
       *订阅事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 5;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订阅事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 5;</code>
       */
      public com.bibox.dex.proto.index.IndexProto.EventType getEvent() {
        com.bibox.dex.proto.index.IndexProto.EventType result = com.bibox.dex.proto.index.IndexProto.EventType.valueOf(event_);
        return result == null ? com.bibox.dex.proto.index.IndexProto.EventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *订阅事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 5;</code>
       */
      public Builder setEvent(com.bibox.dex.proto.index.IndexProto.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订阅事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 5;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:chainindex.api.SubscribeEventRequest)
    }

    // @@protoc_insertion_point(class_scope:chainindex.api.SubscribeEventRequest)
    private static final com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest();
    }

    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeEventRequest>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeEventRequest>() {
      public SubscribeEventRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscribeEventRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeEventRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeEventRequest> getParserForType() {
      return PARSER;
    }

    public com.bibox.dex.proto.index.IndexProto.SubscribeEventRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscribeEventReponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:chainindex.api.SubscribeEventReponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    com.bibox.dex.proto.shared.StatusProto.Status getStatus();
    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>.shared.api.ChainType chain = 2;</code>
     */
    int getChainValue();
    /**
     * <code>.shared.api.ChainType chain = 2;</code>
     */
    com.bibox.dex.proto.shared.TokenProto.ChainType getChain();

    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 3;</code>
     */
    int getEventValue();
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 3;</code>
     */
    com.bibox.dex.proto.index.IndexProto.EventType getEvent();

    /**
     * <pre>
     *订阅地址，也是event的地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     *订阅地址，也是event的地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>int64 block_num = 5;</code>
     */
    long getBlockNum();

    /**
     * <code>int64 block_time = 6;</code>
     */
    long getBlockTime();

    /**
     * <code>string block_hash = 7;</code>
     */
    java.lang.String getBlockHash();
    /**
     * <code>string block_hash = 7;</code>
     */
    com.google.protobuf.ByteString
        getBlockHashBytes();

    /**
     * <pre>
     *tx的完整信息，用户数据尽可能解析出来
     * </pre>
     *
     * <code>string txjson = 8;</code>
     */
    java.lang.String getTxjson();
    /**
     * <pre>
     *tx的完整信息，用户数据尽可能解析出来
     * </pre>
     *
     * <code>string txjson = 8;</code>
     */
    com.google.protobuf.ByteString
        getTxjsonBytes();
  }
  /**
   * Protobuf type {@code chainindex.api.SubscribeEventReponse}
   */
  public  static final class SubscribeEventReponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:chainindex.api.SubscribeEventReponse)
      SubscribeEventReponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeEventReponse.newBuilder() to construct.
    private SubscribeEventReponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeEventReponse() {
      chain_ = 0;
      event_ = 0;
      address_ = "";
      blockNum_ = 0L;
      blockTime_ = 0L;
      blockHash_ = "";
      txjson_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubscribeEventReponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.bibox.dex.proto.shared.StatusProto.Status.Builder subBuilder = null;
              if (status_ != null) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(com.bibox.dex.proto.shared.StatusProto.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              chain_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 40: {

              blockNum_ = input.readInt64();
              break;
            }
            case 48: {

              blockTime_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              blockHash_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              txjson_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventReponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventReponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.class, com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private com.bibox.dex.proto.shared.StatusProto.Status status_;
    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return status_ != null;
    }
    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    public com.bibox.dex.proto.shared.StatusProto.Status getStatus() {
      return status_ == null ? com.bibox.dex.proto.shared.StatusProto.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>.shared.api.Status status = 1;</code>
     */
    public com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder getStatusOrBuilder() {
      return getStatus();
    }

    public static final int CHAIN_FIELD_NUMBER = 2;
    private int chain_;
    /**
     * <code>.shared.api.ChainType chain = 2;</code>
     */
    public int getChainValue() {
      return chain_;
    }
    /**
     * <code>.shared.api.ChainType chain = 2;</code>
     */
    public com.bibox.dex.proto.shared.TokenProto.ChainType getChain() {
      com.bibox.dex.proto.shared.TokenProto.ChainType result = com.bibox.dex.proto.shared.TokenProto.ChainType.valueOf(chain_);
      return result == null ? com.bibox.dex.proto.shared.TokenProto.ChainType.UNRECOGNIZED : result;
    }

    public static final int EVENT_FIELD_NUMBER = 3;
    private int event_;
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 3;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>.chainindex.api.EventType event = 3;</code>
     */
    public com.bibox.dex.proto.index.IndexProto.EventType getEvent() {
      com.bibox.dex.proto.index.IndexProto.EventType result = com.bibox.dex.proto.index.IndexProto.EventType.valueOf(event_);
      return result == null ? com.bibox.dex.proto.index.IndexProto.EventType.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     *订阅地址，也是event的地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *订阅地址，也是event的地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCK_NUM_FIELD_NUMBER = 5;
    private long blockNum_;
    /**
     * <code>int64 block_num = 5;</code>
     */
    public long getBlockNum() {
      return blockNum_;
    }

    public static final int BLOCK_TIME_FIELD_NUMBER = 6;
    private long blockTime_;
    /**
     * <code>int64 block_time = 6;</code>
     */
    public long getBlockTime() {
      return blockTime_;
    }

    public static final int BLOCK_HASH_FIELD_NUMBER = 7;
    private volatile java.lang.Object blockHash_;
    /**
     * <code>string block_hash = 7;</code>
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      }
    }
    /**
     * <code>string block_hash = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXJSON_FIELD_NUMBER = 8;
    private volatile java.lang.Object txjson_;
    /**
     * <pre>
     *tx的完整信息，用户数据尽可能解析出来
     * </pre>
     *
     * <code>string txjson = 8;</code>
     */
    public java.lang.String getTxjson() {
      java.lang.Object ref = txjson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txjson_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *tx的完整信息，用户数据尽可能解析出来
     * </pre>
     *
     * <code>string txjson = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTxjsonBytes() {
      java.lang.Object ref = txjson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txjson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != null) {
        output.writeMessage(1, getStatus());
      }
      if (chain_ != com.bibox.dex.proto.shared.TokenProto.ChainType.CHAIN_UNKNOWN.getNumber()) {
        output.writeEnum(2, chain_);
      }
      if (event_ != com.bibox.dex.proto.index.IndexProto.EventType.EV_TX.getNumber()) {
        output.writeEnum(3, event_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      if (blockNum_ != 0L) {
        output.writeInt64(5, blockNum_);
      }
      if (blockTime_ != 0L) {
        output.writeInt64(6, blockTime_);
      }
      if (!getBlockHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, blockHash_);
      }
      if (!getTxjsonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, txjson_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStatus());
      }
      if (chain_ != com.bibox.dex.proto.shared.TokenProto.ChainType.CHAIN_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, chain_);
      }
      if (event_ != com.bibox.dex.proto.index.IndexProto.EventType.EV_TX.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, event_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      if (blockNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, blockNum_);
      }
      if (blockTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, blockTime_);
      }
      if (!getBlockHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, blockHash_);
      }
      if (!getTxjsonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, txjson_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse)) {
        return super.equals(obj);
      }
      com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse other = (com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && chain_ == other.chain_;
      result = result && event_ == other.event_;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && (getBlockNum()
          == other.getBlockNum());
      result = result && (getBlockTime()
          == other.getBlockTime());
      result = result && getBlockHash()
          .equals(other.getBlockHash());
      result = result && getTxjson()
          .equals(other.getTxjson());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (37 * hash) + CHAIN_FIELD_NUMBER;
      hash = (53 * hash) + chain_;
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + BLOCK_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockNum());
      hash = (37 * hash) + BLOCK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockTime());
      hash = (37 * hash) + BLOCK_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHash().hashCode();
      hash = (37 * hash) + TXJSON_FIELD_NUMBER;
      hash = (53 * hash) + getTxjson().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chainindex.api.SubscribeEventReponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:chainindex.api.SubscribeEventReponse)
        com.bibox.dex.proto.index.IndexProto.SubscribeEventReponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventReponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventReponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.class, com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.Builder.class);
      }

      // Construct using com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          status_ = null;
          statusBuilder_ = null;
        }
        chain_ = 0;

        event_ = 0;

        address_ = "";

        blockNum_ = 0L;

        blockTime_ = 0L;

        blockHash_ = "";

        txjson_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bibox.dex.proto.index.IndexProto.internal_static_chainindex_api_SubscribeEventReponse_descriptor;
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse getDefaultInstanceForType() {
        return com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.getDefaultInstance();
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse build() {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse buildPartial() {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse result = new com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse(this);
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        result.chain_ = chain_;
        result.event_ = event_;
        result.address_ = address_;
        result.blockNum_ = blockNum_;
        result.blockTime_ = blockTime_;
        result.blockHash_ = blockHash_;
        result.txjson_ = txjson_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse) {
          return mergeFrom((com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse other) {
        if (other == com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.chain_ != 0) {
          setChainValue(other.getChainValue());
        }
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getBlockNum() != 0L) {
          setBlockNum(other.getBlockNum());
        }
        if (other.getBlockTime() != 0L) {
          setBlockTime(other.getBlockTime());
        }
        if (!other.getBlockHash().isEmpty()) {
          blockHash_ = other.blockHash_;
          onChanged();
        }
        if (!other.getTxjson().isEmpty()) {
          txjson_ = other.txjson_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.bibox.dex.proto.shared.StatusProto.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bibox.dex.proto.shared.StatusProto.Status, com.bibox.dex.proto.shared.StatusProto.Status.Builder, com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder> statusBuilder_;
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return statusBuilder_ != null || status_ != null;
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public com.bibox.dex.proto.shared.StatusProto.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? com.bibox.dex.proto.shared.StatusProto.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public Builder setStatus(com.bibox.dex.proto.shared.StatusProto.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public Builder setStatus(
          com.bibox.dex.proto.shared.StatusProto.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public Builder mergeStatus(com.bibox.dex.proto.shared.StatusProto.Status value) {
        if (statusBuilder_ == null) {
          if (status_ != null) {
            status_ =
              com.bibox.dex.proto.shared.StatusProto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          status_ = null;
          statusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public com.bibox.dex.proto.shared.StatusProto.Status.Builder getStatusBuilder() {
        
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      public com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              com.bibox.dex.proto.shared.StatusProto.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>.shared.api.Status status = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bibox.dex.proto.shared.StatusProto.Status, com.bibox.dex.proto.shared.StatusProto.Status.Builder, com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bibox.dex.proto.shared.StatusProto.Status, com.bibox.dex.proto.shared.StatusProto.Status.Builder, com.bibox.dex.proto.shared.StatusProto.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      private int chain_ = 0;
      /**
       * <code>.shared.api.ChainType chain = 2;</code>
       */
      public int getChainValue() {
        return chain_;
      }
      /**
       * <code>.shared.api.ChainType chain = 2;</code>
       */
      public Builder setChainValue(int value) {
        chain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.shared.api.ChainType chain = 2;</code>
       */
      public com.bibox.dex.proto.shared.TokenProto.ChainType getChain() {
        com.bibox.dex.proto.shared.TokenProto.ChainType result = com.bibox.dex.proto.shared.TokenProto.ChainType.valueOf(chain_);
        return result == null ? com.bibox.dex.proto.shared.TokenProto.ChainType.UNRECOGNIZED : result;
      }
      /**
       * <code>.shared.api.ChainType chain = 2;</code>
       */
      public Builder setChain(com.bibox.dex.proto.shared.TokenProto.ChainType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chain_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.shared.api.ChainType chain = 2;</code>
       */
      public Builder clearChain() {
        
        chain_ = 0;
        onChanged();
        return this;
      }

      private int event_ = 0;
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 3;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 3;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 3;</code>
       */
      public com.bibox.dex.proto.index.IndexProto.EventType getEvent() {
        com.bibox.dex.proto.index.IndexProto.EventType result = com.bibox.dex.proto.index.IndexProto.EventType.valueOf(event_);
        return result == null ? com.bibox.dex.proto.index.IndexProto.EventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 3;</code>
       */
      public Builder setEvent(com.bibox.dex.proto.index.IndexProto.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>.chainindex.api.EventType event = 3;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       *订阅地址，也是event的地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *订阅地址，也是event的地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *订阅地址，也是event的地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订阅地址，也是event的地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订阅地址，也是event的地址
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private long blockNum_ ;
      /**
       * <code>int64 block_num = 5;</code>
       */
      public long getBlockNum() {
        return blockNum_;
      }
      /**
       * <code>int64 block_num = 5;</code>
       */
      public Builder setBlockNum(long value) {
        
        blockNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 block_num = 5;</code>
       */
      public Builder clearBlockNum() {
        
        blockNum_ = 0L;
        onChanged();
        return this;
      }

      private long blockTime_ ;
      /**
       * <code>int64 block_time = 6;</code>
       */
      public long getBlockTime() {
        return blockTime_;
      }
      /**
       * <code>int64 block_time = 6;</code>
       */
      public Builder setBlockTime(long value) {
        
        blockTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 block_time = 6;</code>
       */
      public Builder clearBlockTime() {
        
        blockTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object blockHash_ = "";
      /**
       * <code>string block_hash = 7;</code>
       */
      public java.lang.String getBlockHash() {
        java.lang.Object ref = blockHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          blockHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string block_hash = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBlockHashBytes() {
        java.lang.Object ref = blockHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blockHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string block_hash = 7;</code>
       */
      public Builder setBlockHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string block_hash = 7;</code>
       */
      public Builder clearBlockHash() {
        
        blockHash_ = getDefaultInstance().getBlockHash();
        onChanged();
        return this;
      }
      /**
       * <code>string block_hash = 7;</code>
       */
      public Builder setBlockHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        blockHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object txjson_ = "";
      /**
       * <pre>
       *tx的完整信息，用户数据尽可能解析出来
       * </pre>
       *
       * <code>string txjson = 8;</code>
       */
      public java.lang.String getTxjson() {
        java.lang.Object ref = txjson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txjson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *tx的完整信息，用户数据尽可能解析出来
       * </pre>
       *
       * <code>string txjson = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTxjsonBytes() {
        java.lang.Object ref = txjson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txjson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *tx的完整信息，用户数据尽可能解析出来
       * </pre>
       *
       * <code>string txjson = 8;</code>
       */
      public Builder setTxjson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txjson_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *tx的完整信息，用户数据尽可能解析出来
       * </pre>
       *
       * <code>string txjson = 8;</code>
       */
      public Builder clearTxjson() {
        
        txjson_ = getDefaultInstance().getTxjson();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *tx的完整信息，用户数据尽可能解析出来
       * </pre>
       *
       * <code>string txjson = 8;</code>
       */
      public Builder setTxjsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txjson_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:chainindex.api.SubscribeEventReponse)
    }

    // @@protoc_insertion_point(class_scope:chainindex.api.SubscribeEventReponse)
    private static final com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse();
    }

    public static com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeEventReponse>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeEventReponse>() {
      public SubscribeEventReponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscribeEventReponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeEventReponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscribeEventReponse> getParserForType() {
      return PARSER;
    }

    public com.bibox.dex.proto.index.IndexProto.SubscribeEventReponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chainindex_api_SubscribeEventRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chainindex_api_SubscribeEventRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chainindex_api_SubscribeEventReponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chainindex_api_SubscribeEventReponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027chain-index/index.proto\022\016chainindex.ap" +
      "i\032\022shared/token.proto\032\023shared/status.pro" +
      "to\"\254\001\n\025SubscribeEventRequest\022$\n\005chain\030\001 " +
      "\001(\0162\025.shared.api.ChainType\022\020\n\010addresss\030\002" +
      " \003(\t\022\027\n\017block_num_start\030\003 \001(\003\022\030\n\020block_t" +
      "ime_start\030\004 \001(\003\022(\n\005event\030\005 \001(\0162\031.chainin" +
      "dex.api.EventType\"\347\001\n\025SubscribeEventRepo" +
      "nse\022\"\n\006status\030\001 \001(\0132\022.shared.api.Status\022" +
      "$\n\005chain\030\002 \001(\0162\025.shared.api.ChainType\022(\n" +
      "\005event\030\003 \001(\0162\031.chainindex.api.EventType\022" +
      "\017\n\007address\030\004 \001(\t\022\021\n\tblock_num\030\005 \001(\003\022\022\n\nb" +
      "lock_time\030\006 \001(\003\022\022\n\nblock_hash\030\007 \001(\t\022\016\n\006t" +
      "xjson\030\010 \001(\t*.\n\tEventType\022\t\n\005EV_TX\020\000\022\n\n\006E" +
      "V_ACT\020\001\022\n\n\005EV_HB\020\346\0072w\n\021ChainIndexService" +
      "\022b\n\016SubscribeEvent\022%.chainindex.api.Subs" +
      "cribeEventRequest\032%.chainindex.api.Subsc" +
      "ribeEventReponse\"\0000\001Be\n\031com.bibox.dex.pr" +
      "oto.indexB\nIndexProtoZ<git.bibox.com/big" +
      "4/protocode.git/chain-index-go;pbchainin" +
      "dexb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bibox.dex.proto.shared.TokenProto.getDescriptor(),
          com.bibox.dex.proto.shared.StatusProto.getDescriptor(),
        }, assigner);
    internal_static_chainindex_api_SubscribeEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chainindex_api_SubscribeEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chainindex_api_SubscribeEventRequest_descriptor,
        new java.lang.String[] { "Chain", "Addresss", "BlockNumStart", "BlockTimeStart", "Event", });
    internal_static_chainindex_api_SubscribeEventReponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chainindex_api_SubscribeEventReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chainindex_api_SubscribeEventReponse_descriptor,
        new java.lang.String[] { "Status", "Chain", "Event", "Address", "BlockNum", "BlockTime", "BlockHash", "Txjson", });
    com.bibox.dex.proto.shared.TokenProto.getDescriptor();
    com.bibox.dex.proto.shared.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
