// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chain-contract/neo-contract.proto

package pbchaincontract // import "github.com/gisvr/protocode/chain-contract-go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import shared_go "github.com/gisvr/protocode/shared-go"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NeoAsset struct {
	Token                *shared_go.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount               float64          `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NeoAsset) Reset()         { *m = NeoAsset{} }
func (m *NeoAsset) String() string { return proto.CompactTextString(m) }
func (*NeoAsset) ProtoMessage()    {}
func (*NeoAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_neo_contract_f8a94235e17a84e1, []int{0}
}
func (m *NeoAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeoAsset.Unmarshal(m, b)
}
func (m *NeoAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeoAsset.Marshal(b, m, deterministic)
}
func (dst *NeoAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeoAsset.Merge(dst, src)
}
func (m *NeoAsset) XXX_Size() int {
	return xxx_messageInfo_NeoAsset.Size(m)
}
func (m *NeoAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_NeoAsset.DiscardUnknown(m)
}

var xxx_messageInfo_NeoAsset proto.InternalMessageInfo

func (m *NeoAsset) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NeoAsset) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type NeoAttrbute struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Usage                string   `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeoAttrbute) Reset()         { *m = NeoAttrbute{} }
func (m *NeoAttrbute) String() string { return proto.CompactTextString(m) }
func (*NeoAttrbute) ProtoMessage()    {}
func (*NeoAttrbute) Descriptor() ([]byte, []int) {
	return fileDescriptor_neo_contract_f8a94235e17a84e1, []int{1}
}
func (m *NeoAttrbute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeoAttrbute.Unmarshal(m, b)
}
func (m *NeoAttrbute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeoAttrbute.Marshal(b, m, deterministic)
}
func (dst *NeoAttrbute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeoAttrbute.Merge(dst, src)
}
func (m *NeoAttrbute) XXX_Size() int {
	return xxx_messageInfo_NeoAttrbute.Size(m)
}
func (m *NeoAttrbute) XXX_DiscardUnknown() {
	xxx_messageInfo_NeoAttrbute.DiscardUnknown(m)
}

var xxx_messageInfo_NeoAttrbute proto.InternalMessageInfo

func (m *NeoAttrbute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NeoAttrbute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NeoAttrbute) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

type NeoInvokeArg struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeoInvokeArg) Reset()         { *m = NeoInvokeArg{} }
func (m *NeoInvokeArg) String() string { return proto.CompactTextString(m) }
func (*NeoInvokeArg) ProtoMessage()    {}
func (*NeoInvokeArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_neo_contract_f8a94235e17a84e1, []int{2}
}
func (m *NeoInvokeArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeoInvokeArg.Unmarshal(m, b)
}
func (m *NeoInvokeArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeoInvokeArg.Marshal(b, m, deterministic)
}
func (dst *NeoInvokeArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeoInvokeArg.Merge(dst, src)
}
func (m *NeoInvokeArg) XXX_Size() int {
	return xxx_messageInfo_NeoInvokeArg.Size(m)
}
func (m *NeoInvokeArg) XXX_DiscardUnknown() {
	xxx_messageInfo_NeoInvokeArg.DiscardUnknown(m)
}

var xxx_messageInfo_NeoInvokeArg proto.InternalMessageInfo

func (m *NeoInvokeArg) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NeoInvokeArg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NeoInvokeParam struct {
	Type                 shared_go.InvokeType `protobuf:"varint,1,opt,name=type,proto3,enum=shared.api.InvokeType" json:"type,omitempty"`
	Args                 []*NeoInvokeArg      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	AttachedAssets       []*NeoAsset          `protobuf:"bytes,3,rep,name=attachedAssets,proto3" json:"attachedAssets,omitempty"`
	Fee                  float64              `protobuf:"fixed64,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Attributes           []*NeoAttrbute       `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	SeqId                string               `protobuf:"bytes,6,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	SignedTransaction    []string             `protobuf:"bytes,7,rep,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	PublicKey            string               `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SpendAddress         string               `protobuf:"bytes,9,opt,name=spendAddress,proto3" json:"spendAddress,omitempty"`
	ToAddress            string               `protobuf:"bytes,10,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NeoInvokeParam) Reset()         { *m = NeoInvokeParam{} }
func (m *NeoInvokeParam) String() string { return proto.CompactTextString(m) }
func (*NeoInvokeParam) ProtoMessage()    {}
func (*NeoInvokeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_neo_contract_f8a94235e17a84e1, []int{3}
}
func (m *NeoInvokeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeoInvokeParam.Unmarshal(m, b)
}
func (m *NeoInvokeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeoInvokeParam.Marshal(b, m, deterministic)
}
func (dst *NeoInvokeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeoInvokeParam.Merge(dst, src)
}
func (m *NeoInvokeParam) XXX_Size() int {
	return xxx_messageInfo_NeoInvokeParam.Size(m)
}
func (m *NeoInvokeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NeoInvokeParam.DiscardUnknown(m)
}

var xxx_messageInfo_NeoInvokeParam proto.InternalMessageInfo

func (m *NeoInvokeParam) GetType() shared_go.InvokeType {
	if m != nil {
		return m.Type
	}
	return shared_go.InvokeType_UNKOWN
}

func (m *NeoInvokeParam) GetArgs() []*NeoInvokeArg {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *NeoInvokeParam) GetAttachedAssets() []*NeoAsset {
	if m != nil {
		return m.AttachedAssets
	}
	return nil
}

func (m *NeoInvokeParam) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *NeoInvokeParam) GetAttributes() []*NeoAttrbute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *NeoInvokeParam) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *NeoInvokeParam) GetSignedTransaction() []string {
	if m != nil {
		return m.SignedTransaction
	}
	return nil
}

func (m *NeoInvokeParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NeoInvokeParam) GetSpendAddress() string {
	if m != nil {
		return m.SpendAddress
	}
	return ""
}

func (m *NeoInvokeParam) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

type NeoInvokeResult struct {
	Script               string          `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	State                string          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	GasConsumed          string          `protobuf:"bytes,3,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	Stack                []*NeoInvokeArg `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack,omitempty"`
	SeqId                string          `protobuf:"bytes,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	EncodedTransaction   []string        `protobuf:"bytes,6,rep,name=encoded_transaction,json=encodedTransaction,proto3" json:"encoded_transaction,omitempty"`
	Txid                 string          `protobuf:"bytes,7,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NeoInvokeResult) Reset()         { *m = NeoInvokeResult{} }
func (m *NeoInvokeResult) String() string { return proto.CompactTextString(m) }
func (*NeoInvokeResult) ProtoMessage()    {}
func (*NeoInvokeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_neo_contract_f8a94235e17a84e1, []int{4}
}
func (m *NeoInvokeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeoInvokeResult.Unmarshal(m, b)
}
func (m *NeoInvokeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeoInvokeResult.Marshal(b, m, deterministic)
}
func (dst *NeoInvokeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeoInvokeResult.Merge(dst, src)
}
func (m *NeoInvokeResult) XXX_Size() int {
	return xxx_messageInfo_NeoInvokeResult.Size(m)
}
func (m *NeoInvokeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NeoInvokeResult.DiscardUnknown(m)
}

var xxx_messageInfo_NeoInvokeResult proto.InternalMessageInfo

func (m *NeoInvokeResult) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *NeoInvokeResult) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *NeoInvokeResult) GetGasConsumed() string {
	if m != nil {
		return m.GasConsumed
	}
	return ""
}

func (m *NeoInvokeResult) GetStack() []*NeoInvokeArg {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *NeoInvokeResult) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *NeoInvokeResult) GetEncodedTransaction() []string {
	if m != nil {
		return m.EncodedTransaction
	}
	return nil
}

func (m *NeoInvokeResult) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func init() {
	proto.RegisterType((*NeoAsset)(nil), "contract.api.NeoAsset")
	proto.RegisterType((*NeoAttrbute)(nil), "contract.api.NeoAttrbute")
	proto.RegisterType((*NeoInvokeArg)(nil), "contract.api.NeoInvokeArg")
	proto.RegisterType((*NeoInvokeParam)(nil), "contract.api.NeoInvokeParam")
	proto.RegisterType((*NeoInvokeResult)(nil), "contract.api.NeoInvokeResult")
}

func init() {
	proto.RegisterFile("chain-contract/neo-contract.proto", fileDescriptor_neo_contract_f8a94235e17a84e1)
}

var fileDescriptor_neo_contract_f8a94235e17a84e1 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0x55, 0xc8, 0x0f, 0xe4, 0x26, 0xe2, 0x83, 0xe1, 0x2b, 0x9a, 0x22, 0x2a, 0x85, 0x6c, 0x1a,
	0x55, 0xc2, 0xae, 0x68, 0x17, 0xad, 0x2a, 0x55, 0x02, 0x56, 0x08, 0x15, 0x21, 0x8b, 0x55, 0x37,
	0xd1, 0xd8, 0x73, 0x6b, 0x46, 0x21, 0x1e, 0xe3, 0xb9, 0x46, 0xc9, 0xdb, 0xf4, 0x11, 0xfb, 0x08,
	0xd5, 0xfc, 0xe0, 0x1a, 0x58, 0xb4, 0x3b, 0x9f, 0x73, 0xcf, 0x39, 0x71, 0xce, 0xbd, 0x09, 0x1c,
	0x65, 0xb7, 0x42, 0x15, 0xc7, 0x99, 0x2e, 0xa8, 0x12, 0x19, 0xc5, 0x05, 0xea, 0x06, 0x44, 0x65,
	0xa5, 0x49, 0xb3, 0x71, 0x83, 0x45, 0xa9, 0x0e, 0x98, 0xb9, 0x15, 0x15, 0xca, 0x98, 0xf4, 0x02,
	0x0b, 0xaf, 0x38, 0xd8, 0x0b, 0x9c, 0x21, 0x41, 0xb5, 0xf1, 0xe4, 0xf4, 0x12, 0xb6, 0xae, 0x50,
	0x9f, 0x1a, 0x83, 0xc4, 0xde, 0x42, 0xdf, 0xe9, 0x79, 0x67, 0xd2, 0x99, 0x8d, 0x4e, 0x76, 0x23,
	0x6f, 0xb0, 0x81, 0xd1, 0x8d, 0x1d, 0x24, 0x7e, 0xce, 0xf6, 0x61, 0x20, 0x96, 0xba, 0x2e, 0x88,
	0x6f, 0x4c, 0x3a, 0xb3, 0x4e, 0x12, 0xd0, 0xf4, 0x1b, 0x8c, 0x6c, 0x18, 0x51, 0x95, 0xd6, 0x84,
	0x8c, 0x41, 0x8f, 0xd6, 0x25, 0xba, 0xb8, 0x61, 0xe2, 0x9e, 0xd9, 0xff, 0xd0, 0x7f, 0x10, 0x77,
	0x35, 0x3a, 0xe7, 0x30, 0xf1, 0xc0, 0xb2, 0xb5, 0x11, 0x39, 0xf2, 0xae, 0x67, 0x1d, 0x98, 0x7e,
	0x82, 0xf1, 0x15, 0xea, 0x8b, 0xe2, 0x41, 0x2f, 0xf0, 0xb4, 0xca, 0xff, 0x3d, 0x6f, 0xfa, 0xb3,
	0x0b, 0xdb, 0x8d, 0xf5, 0x5a, 0x54, 0x62, 0xc9, 0xde, 0xb5, 0xcc, 0xdb, 0x27, 0xfb, 0xed, 0xef,
	0xe6, 0x65, 0x37, 0xeb, 0x12, 0x43, 0x68, 0x04, 0x3d, 0x51, 0xe5, 0x86, 0x6f, 0x4c, 0xba, 0xb3,
	0xd1, 0xc9, 0x41, 0xd4, 0xae, 0x36, 0x6a, 0xbf, 0x52, 0xe2, 0x74, 0xec, 0x2b, 0x6c, 0x0b, 0x22,
	0x91, 0xdd, 0xa2, 0x74, 0x4d, 0x1a, 0xde, 0x75, 0xce, 0xfd, 0x17, 0x4e, 0x37, 0x4e, 0x9e, 0xa9,
	0xd9, 0x0e, 0x74, 0x7f, 0x20, 0xf2, 0x9e, 0x2b, 0xd3, 0x3e, 0xb2, 0xcf, 0x00, 0x82, 0xa8, 0x52,
	0xb6, 0x47, 0xc3, 0xfb, 0x2e, 0xed, 0xf5, 0xcb, 0xb4, 0xd0, 0x74, 0xd2, 0x12, 0xb3, 0x57, 0x30,
	0x30, 0x78, 0x3f, 0x57, 0x92, 0x0f, 0x7c, 0x25, 0x06, 0xef, 0x2f, 0x24, 0x3b, 0x06, 0x66, 0x54,
	0x5e, 0xa0, 0x9c, 0x53, 0x25, 0x0a, 0x23, 0x32, 0x52, 0xba, 0xe0, 0x9b, 0x93, 0xee, 0x6c, 0x98,
	0xec, 0xfa, 0xc9, 0xcd, 0x9f, 0x01, 0x7b, 0x03, 0x50, 0xd6, 0xe9, 0x9d, 0xca, 0xe6, 0x0b, 0x5c,
	0xf3, 0x2d, 0x97, 0x34, 0xf4, 0xcc, 0x25, 0xae, 0xd9, 0x14, 0xc6, 0xa6, 0xc4, 0x42, 0x9e, 0x4a,
	0x59, 0xa1, 0x31, 0x7c, 0xe8, 0x04, 0x4f, 0x38, 0x76, 0x08, 0x43, 0xd2, 0x8f, 0x02, 0xf0, 0x09,
	0x0d, 0x31, 0xfd, 0xd5, 0x81, 0xff, 0x9a, 0x2a, 0x13, 0x34, 0xf5, 0x1d, 0xd9, 0xbb, 0x32, 0x59,
	0xa5, 0x4a, 0x0a, 0x2b, 0x0e, 0xc8, 0x2e, 0xd9, 0x1e, 0x6d, 0xb3, 0x64, 0x07, 0xd8, 0x11, 0x8c,
	0x73, 0x61, 0xe6, 0x99, 0x2e, 0x4c, 0xbd, 0x44, 0x19, 0x6e, 0x67, 0x94, 0x0b, 0x73, 0x1e, 0x28,
	0xf6, 0xde, 0x19, 0xb3, 0x05, 0xef, 0xfd, 0x75, 0x93, 0x5e, 0xd8, 0x6a, 0xaf, 0xdf, 0x6e, 0x2f,
	0x86, 0x3d, 0x2c, 0x32, 0x2d, 0x9f, 0xd5, 0x37, 0x70, 0xf5, 0xb1, 0x30, 0x6a, 0xf7, 0x67, 0x6f,
	0x75, 0xa5, 0x24, 0xdf, 0x0c, 0xb7, 0xba, 0x52, 0xf2, 0x8c, 0xe0, 0x30, 0xd3, 0xcb, 0x28, 0x55,
	0xa9, 0x5e, 0x45, 0x12, 0x57, 0xfe, 0x27, 0xd8, 0xbc, 0xd3, 0xd9, 0xce, 0x15, 0xea, 0xf3, 0x00,
	0xae, 0xed, 0xe8, 0xfb, 0x59, 0xae, 0x28, 0xe8, 0x33, 0xbd, 0x8c, 0x53, 0x95, 0x7f, 0x8c, 0x9d,
	0xc9, 0x7e, 0x5e, 0x94, 0x2b, 0x8a, 0x9f, 0xfe, 0x31, 0x1c, 0xe7, 0xfa, 0x4b, 0x99, 0x3a, 0xee,
	0x91, 0x4a, 0x07, 0xce, 0xf0, 0xe1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xcf, 0x41, 0x66,
	0x44, 0x04, 0x00, 0x00,
}
