# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from chain_query import iost_query_pb2 as chain__query_dot_iost__query__pb2


class IostChainQueryServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAccount = channel.unary_unary(
        '/chainquery.api.IostChainQueryService/GetAccount',
        request_serializer=chain__query_dot_iost__query__pb2.GetAccountRequest.SerializeToString,
        response_deserializer=chain__query_dot_iost__query__pb2.GetAccountResponse.FromString,
        )
    self.GetAccountByPub = channel.unary_unary(
        '/chainquery.api.IostChainQueryService/GetAccountByPub',
        request_serializer=chain__query_dot_iost__query__pb2.GetAccountByPubRequest.SerializeToString,
        response_deserializer=chain__query_dot_iost__query__pb2.GetAccountByPubResponse.FromString,
        )
    self.GetRAMInfo = channel.unary_unary(
        '/chainquery.api.IostChainQueryService/GetRAMInfo',
        request_serializer=chain__query_dot_iost__query__pb2.EmptyRequest.SerializeToString,
        response_deserializer=chain__query_dot_iost__query__pb2.RAMInfoResponse.FromString,
        )
    self.GetGasRatio = channel.unary_unary(
        '/chainquery.api.IostChainQueryService/GetGasRatio',
        request_serializer=chain__query_dot_iost__query__pb2.EmptyRequest.SerializeToString,
        response_deserializer=chain__query_dot_iost__query__pb2.GasRatioResponse.FromString,
        )
    self.GetContractStorage = channel.unary_unary(
        '/chainquery.api.IostChainQueryService/GetContractStorage',
        request_serializer=chain__query_dot_iost__query__pb2.GetContractStorageRequest.SerializeToString,
        response_deserializer=chain__query_dot_iost__query__pb2.GetContractStorageResponse.FromString,
        )


class IostChainQueryServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAccount(self, request, context):
    """get account
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccountByPub(self, request, context):
    """get account by pub_key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRAMInfo(self, request, context):
    """get current blockchain ram information
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGasRatio(self, request, context):
    """get gas ratio infomation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetContractStorage(self, request, context):
    """get contract storage
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IostChainQueryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccount,
          request_deserializer=chain__query_dot_iost__query__pb2.GetAccountRequest.FromString,
          response_serializer=chain__query_dot_iost__query__pb2.GetAccountResponse.SerializeToString,
      ),
      'GetAccountByPub': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountByPub,
          request_deserializer=chain__query_dot_iost__query__pb2.GetAccountByPubRequest.FromString,
          response_serializer=chain__query_dot_iost__query__pb2.GetAccountByPubResponse.SerializeToString,
      ),
      'GetRAMInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetRAMInfo,
          request_deserializer=chain__query_dot_iost__query__pb2.EmptyRequest.FromString,
          response_serializer=chain__query_dot_iost__query__pb2.RAMInfoResponse.SerializeToString,
      ),
      'GetGasRatio': grpc.unary_unary_rpc_method_handler(
          servicer.GetGasRatio,
          request_deserializer=chain__query_dot_iost__query__pb2.EmptyRequest.FromString,
          response_serializer=chain__query_dot_iost__query__pb2.GasRatioResponse.SerializeToString,
      ),
      'GetContractStorage': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractStorage,
          request_deserializer=chain__query_dot_iost__query__pb2.GetContractStorageRequest.FromString,
          response_serializer=chain__query_dot_iost__query__pb2.GetContractStorageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chainquery.api.IostChainQueryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
