# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain-contract/iost-contract.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chain_contract import neo_contract_pb2 as chain__contract_dot_neo__contract__pb2
from shared import status_pb2 as shared_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain-contract/iost-contract.proto',
  package='contract.api',
  syntax='proto3',
  serialized_pb=_b('\n\"chain-contract/iost-contract.proto\x12\x0c\x63ontract.api\x1a!chain-contract/neo-contract.proto\x1a\x13shared/status.proto\"A\n\nIostAction\x12\x10\n\x08\x63ontract\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\xd6\x01\n\x0fIostInvokeParam\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.shared.api.InvokeType\x12\x12\n\npublic_key\x18\x02 \x01(\t\x12\x0e\n\x06seq_id\x18\x03 \x01(\t\x12\x32\n\tsign_type\x18\x04 \x01(\x0e\x32\x1f.contract.api.SignAlgorithmType\x12\x1a\n\x12signed_transaction\x18\x05 \x03(\t\x12)\n\x07\x61\x63tions\x18\x06 \x03(\x0b\x32\x18.contract.api.IostAction\"l\n\x10IostInvokeResult\x12\x0e\n\x06script\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0e\n\x06seq_id\x18\x03 \x01(\t\x12\x1b\n\x13\x65ncoded_transaction\x18\x04 \x03(\t\x12\x0c\n\x04txid\x18\x05 \x01(\t*/\n\x11SignAlgorithmType\x12\r\n\tSecp256k1\x10\x00\x12\x0b\n\x07\x45\x64\x32\x35\x35\x31\x39\x10\x01\x42u\n\x1c\x63om.bibox.dex.proto.contractB\x11IostContractProtoZBgit.bibox.com/big4/protocode.git/chain-contract-go;pbchaincontractb\x06proto3')
  ,
  dependencies=[chain__contract_dot_neo__contract__pb2.DESCRIPTOR,shared_dot_status__pb2.DESCRIPTOR,])

_SIGNALGORITHMTYPE = _descriptor.EnumDescriptor(
  name='SignAlgorithmType',
  full_name='contract.api.SignAlgorithmType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Secp256k1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ed25519', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=502,
  serialized_end=549,
)
_sym_db.RegisterEnumDescriptor(_SIGNALGORITHMTYPE)

SignAlgorithmType = enum_type_wrapper.EnumTypeWrapper(_SIGNALGORITHMTYPE)
Secp256k1 = 0
Ed25519 = 1



_IOSTACTION = _descriptor.Descriptor(
  name='IostAction',
  full_name='contract.api.IostAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='contract.api.IostAction.contract', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_name', full_name='contract.api.IostAction.action_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='contract.api.IostAction.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=173,
)


_IOSTINVOKEPARAM = _descriptor.Descriptor(
  name='IostInvokeParam',
  full_name='contract.api.IostInvokeParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='contract.api.IostInvokeParam.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='contract.api.IostInvokeParam.public_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_id', full_name='contract.api.IostInvokeParam.seq_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign_type', full_name='contract.api.IostInvokeParam.sign_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signed_transaction', full_name='contract.api.IostInvokeParam.signed_transaction', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='contract.api.IostInvokeParam.actions', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=390,
)


_IOSTINVOKERESULT = _descriptor.Descriptor(
  name='IostInvokeResult',
  full_name='contract.api.IostInvokeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='script', full_name='contract.api.IostInvokeResult.script', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='contract.api.IostInvokeResult.state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_id', full_name='contract.api.IostInvokeResult.seq_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoded_transaction', full_name='contract.api.IostInvokeResult.encoded_transaction', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txid', full_name='contract.api.IostInvokeResult.txid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=500,
)

_IOSTINVOKEPARAM.fields_by_name['type'].enum_type = shared_dot_status__pb2._INVOKETYPE
_IOSTINVOKEPARAM.fields_by_name['sign_type'].enum_type = _SIGNALGORITHMTYPE
_IOSTINVOKEPARAM.fields_by_name['actions'].message_type = _IOSTACTION
DESCRIPTOR.message_types_by_name['IostAction'] = _IOSTACTION
DESCRIPTOR.message_types_by_name['IostInvokeParam'] = _IOSTINVOKEPARAM
DESCRIPTOR.message_types_by_name['IostInvokeResult'] = _IOSTINVOKERESULT
DESCRIPTOR.enum_types_by_name['SignAlgorithmType'] = _SIGNALGORITHMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IostAction = _reflection.GeneratedProtocolMessageType('IostAction', (_message.Message,), dict(
  DESCRIPTOR = _IOSTACTION,
  __module__ = 'chain_contract.iost_contract_pb2'
  # @@protoc_insertion_point(class_scope:contract.api.IostAction)
  ))
_sym_db.RegisterMessage(IostAction)

IostInvokeParam = _reflection.GeneratedProtocolMessageType('IostInvokeParam', (_message.Message,), dict(
  DESCRIPTOR = _IOSTINVOKEPARAM,
  __module__ = 'chain_contract.iost_contract_pb2'
  # @@protoc_insertion_point(class_scope:contract.api.IostInvokeParam)
  ))
_sym_db.RegisterMessage(IostInvokeParam)

IostInvokeResult = _reflection.GeneratedProtocolMessageType('IostInvokeResult', (_message.Message,), dict(
  DESCRIPTOR = _IOSTINVOKERESULT,
  __module__ = 'chain_contract.iost_contract_pb2'
  # @@protoc_insertion_point(class_scope:contract.api.IostInvokeResult)
  ))
_sym_db.RegisterMessage(IostInvokeResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.bibox.dex.proto.contractB\021IostContractProtoZBgit.bibox.com/big4/protocode.git/chain-contract-go;pbchaincontract'))
# @@protoc_insertion_point(module_scope)
