# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain-index/index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import token_pb2 as shared_dot_token__pb2
from shared import status_pb2 as shared_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain-index/index.proto',
  package='chainindex.api',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x63hain-index/index.proto\x12\x0e\x63hainindex.api\x1a\x12shared/token.proto\x1a\x13shared/status.proto\"\xac\x01\n\x15SubscribeEventRequest\x12$\n\x05\x63hain\x18\x01 \x01(\x0e\x32\x15.shared.api.ChainType\x12\x10\n\x08\x61\x64\x64resss\x18\x02 \x03(\t\x12\x17\n\x0f\x62lock_num_start\x18\x03 \x01(\x03\x12\x18\n\x10\x62lock_time_start\x18\x04 \x01(\x03\x12(\n\x05\x65vent\x18\x05 \x01(\x0e\x32\x19.chainindex.api.EventType\"\xe7\x01\n\x15SubscribeEventReponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.shared.api.Status\x12$\n\x05\x63hain\x18\x02 \x01(\x0e\x32\x15.shared.api.ChainType\x12(\n\x05\x65vent\x18\x03 \x01(\x0e\x32\x19.chainindex.api.EventType\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x11\n\tblock_num\x18\x05 \x01(\x03\x12\x12\n\nblock_time\x18\x06 \x01(\x03\x12\x12\n\nblock_hash\x18\x07 \x01(\t\x12\x0e\n\x06txjson\x18\x08 \x01(\t*.\n\tEventType\x12\t\n\x05\x45V_TX\x10\x00\x12\n\n\x06\x45V_ACT\x10\x01\x12\n\n\x05\x45V_HB\x10\xe6\x07\x32w\n\x11\x43hainIndexService\x12\x62\n\x0eSubscribeEvent\x12%.chainindex.api.SubscribeEventRequest\x1a%.chainindex.api.SubscribeEventReponse\"\x00\x30\x01\x42\x65\n\x19\x63om.bibox.dex.proto.indexB\nIndexProtoZ<github.com/gisvr/protocode/chain-index-go;pbchainindexb\x06proto3')
  ,
  dependencies=[shared_dot_token__pb2.DESCRIPTOR,shared_dot_status__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='chainindex.api.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EV_TX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EV_ACT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EV_HB', index=2, number=998,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=493,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
EV_TX = 0
EV_ACT = 1
EV_HB = 998



_SUBSCRIBEEVENTREQUEST = _descriptor.Descriptor(
  name='SubscribeEventRequest',
  full_name='chainindex.api.SubscribeEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain', full_name='chainindex.api.SubscribeEventRequest.chain', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addresss', full_name='chainindex.api.SubscribeEventRequest.addresss', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_num_start', full_name='chainindex.api.SubscribeEventRequest.block_num_start', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_time_start', full_name='chainindex.api.SubscribeEventRequest.block_time_start', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='chainindex.api.SubscribeEventRequest.event', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=257,
)


_SUBSCRIBEEVENTREPONSE = _descriptor.Descriptor(
  name='SubscribeEventReponse',
  full_name='chainindex.api.SubscribeEventReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='chainindex.api.SubscribeEventReponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain', full_name='chainindex.api.SubscribeEventReponse.chain', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='chainindex.api.SubscribeEventReponse.event', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='chainindex.api.SubscribeEventReponse.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_num', full_name='chainindex.api.SubscribeEventReponse.block_num', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_time', full_name='chainindex.api.SubscribeEventReponse.block_time', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_hash', full_name='chainindex.api.SubscribeEventReponse.block_hash', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='txjson', full_name='chainindex.api.SubscribeEventReponse.txjson', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=491,
)

_SUBSCRIBEEVENTREQUEST.fields_by_name['chain'].enum_type = shared_dot_token__pb2._CHAINTYPE
_SUBSCRIBEEVENTREQUEST.fields_by_name['event'].enum_type = _EVENTTYPE
_SUBSCRIBEEVENTREPONSE.fields_by_name['status'].message_type = shared_dot_status__pb2._STATUS
_SUBSCRIBEEVENTREPONSE.fields_by_name['chain'].enum_type = shared_dot_token__pb2._CHAINTYPE
_SUBSCRIBEEVENTREPONSE.fields_by_name['event'].enum_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['SubscribeEventRequest'] = _SUBSCRIBEEVENTREQUEST
DESCRIPTOR.message_types_by_name['SubscribeEventReponse'] = _SUBSCRIBEEVENTREPONSE
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeEventRequest = _reflection.GeneratedProtocolMessageType('SubscribeEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEEVENTREQUEST,
  __module__ = 'chain_index.index_pb2'
  # @@protoc_insertion_point(class_scope:chainindex.api.SubscribeEventRequest)
  ))
_sym_db.RegisterMessage(SubscribeEventRequest)

SubscribeEventReponse = _reflection.GeneratedProtocolMessageType('SubscribeEventReponse', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEEVENTREPONSE,
  __module__ = 'chain_index.index_pb2'
  # @@protoc_insertion_point(class_scope:chainindex.api.SubscribeEventReponse)
  ))
_sym_db.RegisterMessage(SubscribeEventReponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.bibox.dex.proto.indexB\nIndexProtoZ<github.com/gisvr/protocode/chain-index-go;pbchainindex'))

_CHAININDEXSERVICE = _descriptor.ServiceDescriptor(
  name='ChainIndexService',
  full_name='chainindex.api.ChainIndexService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=541,
  serialized_end=660,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeEvent',
    full_name='chainindex.api.ChainIndexService.SubscribeEvent',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEEVENTREQUEST,
    output_type=_SUBSCRIBEEVENTREPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAININDEXSERVICE)

DESCRIPTOR.services_by_name['ChainIndexService'] = _CHAININDEXSERVICE

# @@protoc_insertion_point(module_scope)
