// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chain-query/iost-query.proto

package pbchainquery // import "github.com/gisvr/protocode/chain-query-go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import shared_go "github.com/gisvr/protocode/shared-go"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The message defines the account's frozen balance.
type FrozenBalance struct {
	// balance amount
	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// free time
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrozenBalance) Reset()         { *m = FrozenBalance{} }
func (m *FrozenBalance) String() string { return proto.CompactTextString(m) }
func (*FrozenBalance) ProtoMessage()    {}
func (*FrozenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{0}
}
func (m *FrozenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrozenBalance.Unmarshal(m, b)
}
func (m *FrozenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrozenBalance.Marshal(b, m, deterministic)
}
func (dst *FrozenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrozenBalance.Merge(dst, src)
}
func (m *FrozenBalance) XXX_Size() int {
	return xxx_messageInfo_FrozenBalance.Size(m)
}
func (m *FrozenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_FrozenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_FrozenBalance proto.InternalMessageInfo

func (m *FrozenBalance) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *FrozenBalance) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// The message defines the account's vote info.
type VoteInfo struct {
	// option name
	Option string `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	// votes
	Votes float64 `protobuf:"fixed64,2,opt,name=votes,proto3" json:"votes,omitempty"`
	// cleared votes
	ClearedVotes         float64  `protobuf:"fixed64,3,opt,name=cleared_votes,json=clearedVotes,proto3" json:"cleared_votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteInfo) Reset()         { *m = VoteInfo{} }
func (m *VoteInfo) String() string { return proto.CompactTextString(m) }
func (*VoteInfo) ProtoMessage()    {}
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{1}
}
func (m *VoteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteInfo.Unmarshal(m, b)
}
func (m *VoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteInfo.Marshal(b, m, deterministic)
}
func (dst *VoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteInfo.Merge(dst, src)
}
func (m *VoteInfo) XXX_Size() int {
	return xxx_messageInfo_VoteInfo.Size(m)
}
func (m *VoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteInfo proto.InternalMessageInfo

func (m *VoteInfo) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *VoteInfo) GetVotes() float64 {
	if m != nil {
		return m.Votes
	}
	return 0
}

func (m *VoteInfo) GetClearedVotes() float64 {
	if m != nil {
		return m.ClearedVotes
	}
	return 0
}

// The message defines account struct.
type Account struct {
	// account name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// account balance
	Balance float64 `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// gas information
	GasInfo *Account_GasInfo `protobuf:"bytes,3,opt,name=gas_info,json=gasInfo,proto3" json:"gas_info,omitempty"`
	// ram information
	RamInfo *Account_RAMInfo `protobuf:"bytes,4,opt,name=ram_info,json=ramInfo,proto3" json:"ram_info,omitempty"`
	// account permission
	Permissions map[string]*Account_Permission `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// account groups
	Groups map[string]*Account_Group `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// frozen balance information
	FrozenBalances []*FrozenBalance `protobuf:"bytes,7,rep,name=frozen_balances,json=frozenBalances,proto3" json:"frozen_balances,omitempty"`
	// vote information
	VoteInfos            []*VoteInfo `protobuf:"bytes,8,rep,name=vote_infos,json=voteInfos,proto3" json:"vote_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetGasInfo() *Account_GasInfo {
	if m != nil {
		return m.GasInfo
	}
	return nil
}

func (m *Account) GetRamInfo() *Account_RAMInfo {
	if m != nil {
		return m.RamInfo
	}
	return nil
}

func (m *Account) GetPermissions() map[string]*Account_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Account) GetGroups() map[string]*Account_Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Account) GetFrozenBalances() []*FrozenBalance {
	if m != nil {
		return m.FrozenBalances
	}
	return nil
}

func (m *Account) GetVoteInfos() []*VoteInfo {
	if m != nil {
		return m.VoteInfos
	}
	return nil
}

// The message defines account pledged coin information.
type Account_PledgeInfo struct {
	// the account who pledges
	Pledger string `protobuf:"bytes,1,opt,name=pledger,proto3" json:"pledger,omitempty"`
	// pledged amount
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_PledgeInfo) Reset()         { *m = Account_PledgeInfo{} }
func (m *Account_PledgeInfo) String() string { return proto.CompactTextString(m) }
func (*Account_PledgeInfo) ProtoMessage()    {}
func (*Account_PledgeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 0}
}
func (m *Account_PledgeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_PledgeInfo.Unmarshal(m, b)
}
func (m *Account_PledgeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_PledgeInfo.Marshal(b, m, deterministic)
}
func (dst *Account_PledgeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_PledgeInfo.Merge(dst, src)
}
func (m *Account_PledgeInfo) XXX_Size() int {
	return xxx_messageInfo_Account_PledgeInfo.Size(m)
}
func (m *Account_PledgeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_PledgeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Account_PledgeInfo proto.InternalMessageInfo

func (m *Account_PledgeInfo) GetPledger() string {
	if m != nil {
		return m.Pledger
	}
	return ""
}

func (m *Account_PledgeInfo) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// The message defines account gas information.
type Account_GasInfo struct {
	// current total gas amount
	CurrentTotal    float64 `protobuf:"fixed64,1,opt,name=current_total,json=currentTotal,proto3" json:"current_total,omitempty"`
	TransferableGas float64 `protobuf:"fixed64,2,opt,name=transferable_gas,json=transferableGas,proto3" json:"transferable_gas,omitempty"`
	PledgeGas       float64 `protobuf:"fixed64,3,opt,name=pledge_gas,json=pledgeGas,proto3" json:"pledge_gas,omitempty"`
	// gas increase speed
	IncreaseSpeed float64 `protobuf:"fixed64,4,opt,name=increase_speed,json=increaseSpeed,proto3" json:"increase_speed,omitempty"`
	// gas limit
	Limit float64 `protobuf:"fixed64,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// pledge information
	PledgedInfo          []*Account_PledgeInfo `protobuf:"bytes,6,rep,name=pledged_info,json=pledgedInfo,proto3" json:"pledged_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Account_GasInfo) Reset()         { *m = Account_GasInfo{} }
func (m *Account_GasInfo) String() string { return proto.CompactTextString(m) }
func (*Account_GasInfo) ProtoMessage()    {}
func (*Account_GasInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 1}
}
func (m *Account_GasInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_GasInfo.Unmarshal(m, b)
}
func (m *Account_GasInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_GasInfo.Marshal(b, m, deterministic)
}
func (dst *Account_GasInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_GasInfo.Merge(dst, src)
}
func (m *Account_GasInfo) XXX_Size() int {
	return xxx_messageInfo_Account_GasInfo.Size(m)
}
func (m *Account_GasInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_GasInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Account_GasInfo proto.InternalMessageInfo

func (m *Account_GasInfo) GetCurrentTotal() float64 {
	if m != nil {
		return m.CurrentTotal
	}
	return 0
}

func (m *Account_GasInfo) GetTransferableGas() float64 {
	if m != nil {
		return m.TransferableGas
	}
	return 0
}

func (m *Account_GasInfo) GetPledgeGas() float64 {
	if m != nil {
		return m.PledgeGas
	}
	return 0
}

func (m *Account_GasInfo) GetIncreaseSpeed() float64 {
	if m != nil {
		return m.IncreaseSpeed
	}
	return 0
}

func (m *Account_GasInfo) GetLimit() float64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Account_GasInfo) GetPledgedInfo() []*Account_PledgeInfo {
	if m != nil {
		return m.PledgedInfo
	}
	return nil
}

// The message defines account ram information.
type Account_RAMInfo struct {
	// available ram bytes
	Available int64 `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// used ram bytes
	Used int64 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	// total ram bytes
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_RAMInfo) Reset()         { *m = Account_RAMInfo{} }
func (m *Account_RAMInfo) String() string { return proto.CompactTextString(m) }
func (*Account_RAMInfo) ProtoMessage()    {}
func (*Account_RAMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 2}
}
func (m *Account_RAMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_RAMInfo.Unmarshal(m, b)
}
func (m *Account_RAMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_RAMInfo.Marshal(b, m, deterministic)
}
func (dst *Account_RAMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_RAMInfo.Merge(dst, src)
}
func (m *Account_RAMInfo) XXX_Size() int {
	return xxx_messageInfo_Account_RAMInfo.Size(m)
}
func (m *Account_RAMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_RAMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Account_RAMInfo proto.InternalMessageInfo

func (m *Account_RAMInfo) GetAvailable() int64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Account_RAMInfo) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *Account_RAMInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// The message defines permission item.
type Account_Item struct {
	// permission name or key pair id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// whether it's a key pair
	IsKeyPair bool `protobuf:"varint,2,opt,name=is_key_pair,json=isKeyPair,proto3" json:"is_key_pair,omitempty"`
	// permission weight
	Weight int64 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// permission
	Permission           string   `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_Item) Reset()         { *m = Account_Item{} }
func (m *Account_Item) String() string { return proto.CompactTextString(m) }
func (*Account_Item) ProtoMessage()    {}
func (*Account_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 3}
}
func (m *Account_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_Item.Unmarshal(m, b)
}
func (m *Account_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_Item.Marshal(b, m, deterministic)
}
func (dst *Account_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_Item.Merge(dst, src)
}
func (m *Account_Item) XXX_Size() int {
	return xxx_messageInfo_Account_Item.Size(m)
}
func (m *Account_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Account_Item proto.InternalMessageInfo

func (m *Account_Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account_Item) GetIsKeyPair() bool {
	if m != nil {
		return m.IsKeyPair
	}
	return false
}

func (m *Account_Item) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Account_Item) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

// The message defines a permission group.
type Account_Group struct {
	// group name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// permission items
	Items                []*Account_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Account_Group) Reset()         { *m = Account_Group{} }
func (m *Account_Group) String() string { return proto.CompactTextString(m) }
func (*Account_Group) ProtoMessage()    {}
func (*Account_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 4}
}
func (m *Account_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_Group.Unmarshal(m, b)
}
func (m *Account_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_Group.Marshal(b, m, deterministic)
}
func (dst *Account_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_Group.Merge(dst, src)
}
func (m *Account_Group) XXX_Size() int {
	return xxx_messageInfo_Account_Group.Size(m)
}
func (m *Account_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Account_Group proto.InternalMessageInfo

func (m *Account_Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account_Group) GetItems() []*Account_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// The message defines the permission struct.
type Account_Permission struct {
	// permission name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// permission groups
	GroupNames []string `protobuf:"bytes,2,rep,name=group_names,json=groupNames,proto3" json:"group_names,omitempty"`
	// permission items
	Items []*Account_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// permission threshold
	Threshold            int64    `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_Permission) Reset()         { *m = Account_Permission{} }
func (m *Account_Permission) String() string { return proto.CompactTextString(m) }
func (*Account_Permission) ProtoMessage()    {}
func (*Account_Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{2, 5}
}
func (m *Account_Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_Permission.Unmarshal(m, b)
}
func (m *Account_Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_Permission.Marshal(b, m, deterministic)
}
func (dst *Account_Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_Permission.Merge(dst, src)
}
func (m *Account_Permission) XXX_Size() int {
	return xxx_messageInfo_Account_Permission.Size(m)
}
func (m *Account_Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Account_Permission proto.InternalMessageInfo

func (m *Account_Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account_Permission) GetGroupNames() []string {
	if m != nil {
		return m.GroupNames
	}
	return nil
}

func (m *Account_Permission) GetItems() []*Account_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Account_Permission) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type RAMInfo struct {
	// how many bytes have been used
	UsedRam int64 `protobuf:"varint,1,opt,name=used_ram,json=usedRam,proto3" json:"used_ram,omitempty"`
	// how many bytes have not been used
	AvailableRam int64 `protobuf:"varint,2,opt,name=available_ram,json=availableRam,proto3" json:"available_ram,omitempty"`
	// total ram byte
	TotalRam int64 `protobuf:"varint,3,opt,name=total_ram,json=totalRam,proto3" json:"total_ram,omitempty"`
	// User can sell NUM bytes RAM to system to get `NUM * sell_price` IOSTs
	SellPrice float64 `protobuf:"fixed64,4,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// User can spend approximate `NUM * buy_price` IOSTs for NUM bytes RAM
	BuyPrice             float64  `protobuf:"fixed64,5,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RAMInfo) Reset()         { *m = RAMInfo{} }
func (m *RAMInfo) String() string { return proto.CompactTextString(m) }
func (*RAMInfo) ProtoMessage()    {}
func (*RAMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{3}
}
func (m *RAMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RAMInfo.Unmarshal(m, b)
}
func (m *RAMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RAMInfo.Marshal(b, m, deterministic)
}
func (dst *RAMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RAMInfo.Merge(dst, src)
}
func (m *RAMInfo) XXX_Size() int {
	return xxx_messageInfo_RAMInfo.Size(m)
}
func (m *RAMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RAMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RAMInfo proto.InternalMessageInfo

func (m *RAMInfo) GetUsedRam() int64 {
	if m != nil {
		return m.UsedRam
	}
	return 0
}

func (m *RAMInfo) GetAvailableRam() int64 {
	if m != nil {
		return m.AvailableRam
	}
	return 0
}

func (m *RAMInfo) GetTotalRam() int64 {
	if m != nil {
		return m.TotalRam
	}
	return 0
}

func (m *RAMInfo) GetSellPrice() float64 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *RAMInfo) GetBuyPrice() float64 {
	if m != nil {
		return m.BuyPrice
	}
	return 0
}

type GasRatio struct {
	LowestGasRatio       float64  `protobuf:"fixed64,1,opt,name=lowest_gas_ratio,json=lowestGasRatio,proto3" json:"lowest_gas_ratio,omitempty"`
	MedianGasRatio       float64  `protobuf:"fixed64,2,opt,name=median_gas_ratio,json=medianGasRatio,proto3" json:"median_gas_ratio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasRatio) Reset()         { *m = GasRatio{} }
func (m *GasRatio) String() string { return proto.CompactTextString(m) }
func (*GasRatio) ProtoMessage()    {}
func (*GasRatio) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{4}
}
func (m *GasRatio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasRatio.Unmarshal(m, b)
}
func (m *GasRatio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasRatio.Marshal(b, m, deterministic)
}
func (dst *GasRatio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasRatio.Merge(dst, src)
}
func (m *GasRatio) XXX_Size() int {
	return xxx_messageInfo_GasRatio.Size(m)
}
func (m *GasRatio) XXX_DiscardUnknown() {
	xxx_messageInfo_GasRatio.DiscardUnknown(m)
}

var xxx_messageInfo_GasRatio proto.InternalMessageInfo

func (m *GasRatio) GetLowestGasRatio() float64 {
	if m != nil {
		return m.LowestGasRatio
	}
	return 0
}

func (m *GasRatio) GetMedianGasRatio() float64 {
	if m != nil {
		return m.MedianGasRatio
	}
	return 0
}

type GetAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ByLongestChain       bool     `protobuf:"varint,2,opt,name=by_longest_chain,json=byLongestChain,proto3" json:"by_longest_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{5}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAccountRequest) GetByLongestChain() bool {
	if m != nil {
		return m.ByLongestChain
	}
	return false
}

type GetAccountResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Account              string            `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{6}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(dst, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetAccountResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetAccountByPubRequest struct {
	PubKey               string   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	ByLongestChain       bool     `protobuf:"varint,2,opt,name=by_longest_chain,json=byLongestChain,proto3" json:"by_longest_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountByPubRequest) Reset()         { *m = GetAccountByPubRequest{} }
func (m *GetAccountByPubRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountByPubRequest) ProtoMessage()    {}
func (*GetAccountByPubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{7}
}
func (m *GetAccountByPubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByPubRequest.Unmarshal(m, b)
}
func (m *GetAccountByPubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByPubRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountByPubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByPubRequest.Merge(dst, src)
}
func (m *GetAccountByPubRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountByPubRequest.Size(m)
}
func (m *GetAccountByPubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByPubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByPubRequest proto.InternalMessageInfo

func (m *GetAccountByPubRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *GetAccountByPubRequest) GetByLongestChain() bool {
	if m != nil {
		return m.ByLongestChain
	}
	return false
}

type GetAccountByPubResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Accounts             []string          `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAccountByPubResponse) Reset()         { *m = GetAccountByPubResponse{} }
func (m *GetAccountByPubResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountByPubResponse) ProtoMessage()    {}
func (*GetAccountByPubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{8}
}
func (m *GetAccountByPubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByPubResponse.Unmarshal(m, b)
}
func (m *GetAccountByPubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByPubResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountByPubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByPubResponse.Merge(dst, src)
}
func (m *GetAccountByPubResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountByPubResponse.Size(m)
}
func (m *GetAccountByPubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByPubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByPubResponse proto.InternalMessageInfo

func (m *GetAccountByPubResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetAccountByPubResponse) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type RAMInfoResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RamInfo              string            `protobuf:"bytes,2,opt,name=ram_info,json=ramInfo,proto3" json:"ram_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RAMInfoResponse) Reset()         { *m = RAMInfoResponse{} }
func (m *RAMInfoResponse) String() string { return proto.CompactTextString(m) }
func (*RAMInfoResponse) ProtoMessage()    {}
func (*RAMInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{9}
}
func (m *RAMInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RAMInfoResponse.Unmarshal(m, b)
}
func (m *RAMInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RAMInfoResponse.Marshal(b, m, deterministic)
}
func (dst *RAMInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RAMInfoResponse.Merge(dst, src)
}
func (m *RAMInfoResponse) XXX_Size() int {
	return xxx_messageInfo_RAMInfoResponse.Size(m)
}
func (m *RAMInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RAMInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RAMInfoResponse proto.InternalMessageInfo

func (m *RAMInfoResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RAMInfoResponse) GetRamInfo() string {
	if m != nil {
		return m.RamInfo
	}
	return ""
}

type GasRatioResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GasRadio             string            `protobuf:"bytes,2,opt,name=gas_radio,json=gasRadio,proto3" json:"gas_radio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GasRatioResponse) Reset()         { *m = GasRatioResponse{} }
func (m *GasRatioResponse) String() string { return proto.CompactTextString(m) }
func (*GasRatioResponse) ProtoMessage()    {}
func (*GasRatioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{10}
}
func (m *GasRatioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasRatioResponse.Unmarshal(m, b)
}
func (m *GasRatioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasRatioResponse.Marshal(b, m, deterministic)
}
func (dst *GasRatioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasRatioResponse.Merge(dst, src)
}
func (m *GasRatioResponse) XXX_Size() int {
	return xxx_messageInfo_GasRatioResponse.Size(m)
}
func (m *GasRatioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GasRatioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GasRatioResponse proto.InternalMessageInfo

func (m *GasRatioResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GasRatioResponse) GetGasRadio() string {
	if m != nil {
		return m.GasRadio
	}
	return ""
}

// The message defines get contract storage request.
type GetContractStorageRequest struct {
	// contract id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the key in the StateDB
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// get the value from StateDB, field is needed if StateDB[key] is a map.(we get StateDB[key][field] in this case)
	Field string `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	// get data by longest chain's head block or last irreversible block
	ByLongestChain       bool     `protobuf:"varint,4,opt,name=by_longest_chain,json=byLongestChain,proto3" json:"by_longest_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContractStorageRequest) Reset()         { *m = GetContractStorageRequest{} }
func (m *GetContractStorageRequest) String() string { return proto.CompactTextString(m) }
func (*GetContractStorageRequest) ProtoMessage()    {}
func (*GetContractStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{11}
}
func (m *GetContractStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContractStorageRequest.Unmarshal(m, b)
}
func (m *GetContractStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContractStorageRequest.Marshal(b, m, deterministic)
}
func (dst *GetContractStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContractStorageRequest.Merge(dst, src)
}
func (m *GetContractStorageRequest) XXX_Size() int {
	return xxx_messageInfo_GetContractStorageRequest.Size(m)
}
func (m *GetContractStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContractStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContractStorageRequest proto.InternalMessageInfo

func (m *GetContractStorageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetContractStorageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetContractStorageRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GetContractStorageRequest) GetByLongestChain() bool {
	if m != nil {
		return m.ByLongestChain
	}
	return false
}

// The message defines get contract storage response.
type ContractStorage struct {
	// the json string data
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// block hash
	BlockHash string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// block number
	BlockNumber          int64    `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractStorage) Reset()         { *m = ContractStorage{} }
func (m *ContractStorage) String() string { return proto.CompactTextString(m) }
func (*ContractStorage) ProtoMessage()    {}
func (*ContractStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{12}
}
func (m *ContractStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractStorage.Unmarshal(m, b)
}
func (m *ContractStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractStorage.Marshal(b, m, deterministic)
}
func (dst *ContractStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractStorage.Merge(dst, src)
}
func (m *ContractStorage) XXX_Size() int {
	return xxx_messageInfo_ContractStorage.Size(m)
}
func (m *ContractStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractStorage.DiscardUnknown(m)
}

var xxx_messageInfo_ContractStorage proto.InternalMessageInfo

func (m *ContractStorage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ContractStorage) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *ContractStorage) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type GetContractStorageResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ContractStorage      string            `protobuf:"bytes,2,opt,name=contract_storage,json=contractStorage,proto3" json:"contract_storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetContractStorageResponse) Reset()         { *m = GetContractStorageResponse{} }
func (m *GetContractStorageResponse) String() string { return proto.CompactTextString(m) }
func (*GetContractStorageResponse) ProtoMessage()    {}
func (*GetContractStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{13}
}
func (m *GetContractStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContractStorageResponse.Unmarshal(m, b)
}
func (m *GetContractStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContractStorageResponse.Marshal(b, m, deterministic)
}
func (dst *GetContractStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContractStorageResponse.Merge(dst, src)
}
func (m *GetContractStorageResponse) XXX_Size() int {
	return xxx_messageInfo_GetContractStorageResponse.Size(m)
}
func (m *GetContractStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContractStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContractStorageResponse proto.InternalMessageInfo

func (m *GetContractStorageResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetContractStorageResponse) GetContractStorage() string {
	if m != nil {
		return m.ContractStorage
	}
	return ""
}

// The message defines an empty request.
type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_iost_query_fc837d5a69cffc4f, []int{14}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FrozenBalance)(nil), "chainquery.api.FrozenBalance")
	proto.RegisterType((*VoteInfo)(nil), "chainquery.api.VoteInfo")
	proto.RegisterType((*Account)(nil), "chainquery.api.Account")
	proto.RegisterMapType((map[string]*Account_Group)(nil), "chainquery.api.Account.GroupsEntry")
	proto.RegisterMapType((map[string]*Account_Permission)(nil), "chainquery.api.Account.PermissionsEntry")
	proto.RegisterType((*Account_PledgeInfo)(nil), "chainquery.api.Account.PledgeInfo")
	proto.RegisterType((*Account_GasInfo)(nil), "chainquery.api.Account.GasInfo")
	proto.RegisterType((*Account_RAMInfo)(nil), "chainquery.api.Account.RAMInfo")
	proto.RegisterType((*Account_Item)(nil), "chainquery.api.Account.Item")
	proto.RegisterType((*Account_Group)(nil), "chainquery.api.Account.Group")
	proto.RegisterType((*Account_Permission)(nil), "chainquery.api.Account.Permission")
	proto.RegisterType((*RAMInfo)(nil), "chainquery.api.RAMInfo")
	proto.RegisterType((*GasRatio)(nil), "chainquery.api.GasRatio")
	proto.RegisterType((*GetAccountRequest)(nil), "chainquery.api.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "chainquery.api.GetAccountResponse")
	proto.RegisterType((*GetAccountByPubRequest)(nil), "chainquery.api.GetAccountByPubRequest")
	proto.RegisterType((*GetAccountByPubResponse)(nil), "chainquery.api.GetAccountByPubResponse")
	proto.RegisterType((*RAMInfoResponse)(nil), "chainquery.api.RAMInfoResponse")
	proto.RegisterType((*GasRatioResponse)(nil), "chainquery.api.GasRatioResponse")
	proto.RegisterType((*GetContractStorageRequest)(nil), "chainquery.api.GetContractStorageRequest")
	proto.RegisterType((*ContractStorage)(nil), "chainquery.api.ContractStorage")
	proto.RegisterType((*GetContractStorageResponse)(nil), "chainquery.api.GetContractStorageResponse")
	proto.RegisterType((*EmptyRequest)(nil), "chainquery.api.EmptyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IostChainQueryServiceClient is the client API for IostChainQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IostChainQueryServiceClient interface {
	// get account
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	// get account by pub_key
	GetAccountByPub(ctx context.Context, in *GetAccountByPubRequest, opts ...grpc.CallOption) (*GetAccountByPubResponse, error)
	// get current blockchain ram information
	GetRAMInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RAMInfoResponse, error)
	// get gas ratio infomation
	GetGasRatio(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GasRatioResponse, error)
	// get contract storage
	GetContractStorage(ctx context.Context, in *GetContractStorageRequest, opts ...grpc.CallOption) (*GetContractStorageResponse, error)
}

type iostChainQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewIostChainQueryServiceClient(cc *grpc.ClientConn) IostChainQueryServiceClient {
	return &iostChainQueryServiceClient{cc}
}

func (c *iostChainQueryServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.IostChainQueryService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iostChainQueryServiceClient) GetAccountByPub(ctx context.Context, in *GetAccountByPubRequest, opts ...grpc.CallOption) (*GetAccountByPubResponse, error) {
	out := new(GetAccountByPubResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.IostChainQueryService/GetAccountByPub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iostChainQueryServiceClient) GetRAMInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RAMInfoResponse, error) {
	out := new(RAMInfoResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.IostChainQueryService/GetRAMInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iostChainQueryServiceClient) GetGasRatio(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GasRatioResponse, error) {
	out := new(GasRatioResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.IostChainQueryService/GetGasRatio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iostChainQueryServiceClient) GetContractStorage(ctx context.Context, in *GetContractStorageRequest, opts ...grpc.CallOption) (*GetContractStorageResponse, error) {
	out := new(GetContractStorageResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.IostChainQueryService/GetContractStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IostChainQueryServiceServer is the server API for IostChainQueryService service.
type IostChainQueryServiceServer interface {
	// get account
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	// get account by pub_key
	GetAccountByPub(context.Context, *GetAccountByPubRequest) (*GetAccountByPubResponse, error)
	// get current blockchain ram information
	GetRAMInfo(context.Context, *EmptyRequest) (*RAMInfoResponse, error)
	// get gas ratio infomation
	GetGasRatio(context.Context, *EmptyRequest) (*GasRatioResponse, error)
	// get contract storage
	GetContractStorage(context.Context, *GetContractStorageRequest) (*GetContractStorageResponse, error)
}

func RegisterIostChainQueryServiceServer(s *grpc.Server, srv IostChainQueryServiceServer) {
	s.RegisterService(&_IostChainQueryService_serviceDesc, srv)
}

func _IostChainQueryService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IostChainQueryServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.IostChainQueryService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IostChainQueryServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IostChainQueryService_GetAccountByPub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByPubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IostChainQueryServiceServer).GetAccountByPub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.IostChainQueryService/GetAccountByPub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IostChainQueryServiceServer).GetAccountByPub(ctx, req.(*GetAccountByPubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IostChainQueryService_GetRAMInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IostChainQueryServiceServer).GetRAMInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.IostChainQueryService/GetRAMInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IostChainQueryServiceServer).GetRAMInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IostChainQueryService_GetGasRatio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IostChainQueryServiceServer).GetGasRatio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.IostChainQueryService/GetGasRatio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IostChainQueryServiceServer).GetGasRatio(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IostChainQueryService_GetContractStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IostChainQueryServiceServer).GetContractStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.IostChainQueryService/GetContractStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IostChainQueryServiceServer).GetContractStorage(ctx, req.(*GetContractStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IostChainQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainquery.api.IostChainQueryService",
	HandlerType: (*IostChainQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _IostChainQueryService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountByPub",
			Handler:    _IostChainQueryService_GetAccountByPub_Handler,
		},
		{
			MethodName: "GetRAMInfo",
			Handler:    _IostChainQueryService_GetRAMInfo_Handler,
		},
		{
			MethodName: "GetGasRatio",
			Handler:    _IostChainQueryService_GetGasRatio_Handler,
		},
		{
			MethodName: "GetContractStorage",
			Handler:    _IostChainQueryService_GetContractStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chain-query/iost-query.proto",
}

func init() {
	proto.RegisterFile("chain-query/iost-query.proto", fileDescriptor_iost_query_fc837d5a69cffc4f)
}

var fileDescriptor_iost_query_fc837d5a69cffc4f = []byte{
	// 1397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x5f, 0x6f, 0x13, 0xc7,
	0x16, 0xd7, 0xc6, 0x71, 0x6c, 0x1f, 0x3b, 0x8e, 0xef, 0xc0, 0x05, 0x67, 0x49, 0x20, 0x2c, 0xe2,
	0x12, 0x90, 0x62, 0x4b, 0xe1, 0x56, 0x45, 0x50, 0x55, 0x22, 0x08, 0xd2, 0x94, 0x16, 0xc2, 0x06,
	0x55, 0x08, 0xd4, 0x6e, 0x67, 0xd7, 0x93, 0xf5, 0x28, 0xbb, 0x3b, 0xcb, 0xce, 0x6c, 0xc0, 0x45,
	0xbc, 0xf0, 0x5a, 0xf5, 0x89, 0xa7, 0xbe, 0xf6, 0x2b, 0xf5, 0x0b, 0xf4, 0xa1, 0x1f, 0xa3, 0x0f,
	0xd5, 0xfc, 0x59, 0x7b, 0xe3, 0x38, 0x29, 0xcd, 0xdb, 0x9c, 0xdf, 0x9c, 0xf3, 0x9b, 0xb3, 0xe7,
	0xfc, 0xce, 0x8c, 0x0d, 0x2b, 0xc1, 0x10, 0xd3, 0x64, 0xe3, 0x75, 0x4e, 0xb2, 0x51, 0x9f, 0x32,
	0x2e, 0xf4, 0xb2, 0x97, 0x66, 0x4c, 0x30, 0xd4, 0x56, 0xbb, 0x1a, 0xc1, 0x29, 0xb5, 0x57, 0x42,
	0xc6, 0xc2, 0x88, 0xf4, 0x71, 0x4a, 0xfb, 0x38, 0x49, 0x98, 0xc0, 0x82, 0xb2, 0x84, 0x6b, 0x6f,
	0x1b, 0xf1, 0x21, 0xce, 0xc8, 0xa0, 0x2f, 0xd8, 0x01, 0x49, 0x0c, 0x76, 0xce, 0x60, 0x5c, 0x60,
	0x91, 0x1b, 0x47, 0xe7, 0x1e, 0x2c, 0x3e, 0xca, 0xd8, 0x4f, 0x24, 0xd9, 0xc2, 0x11, 0x4e, 0x02,
	0x82, 0x2e, 0xc0, 0x02, 0x8e, 0x59, 0x9e, 0x88, 0xae, 0xb5, 0x66, 0xad, 0x5b, 0xae, 0xb1, 0x10,
	0x82, 0x79, 0x41, 0x63, 0xd2, 0x9d, 0x5b, 0xb3, 0xd6, 0x2b, 0xae, 0x5a, 0x3b, 0xdf, 0x43, 0xfd,
	0x3b, 0x26, 0xc8, 0x4e, 0xb2, 0xcf, 0x64, 0x1c, 0x4b, 0x65, 0x0a, 0x2a, 0xae, 0xe1, 0x1a, 0x0b,
	0x9d, 0x87, 0xea, 0x21, 0x13, 0x84, 0xab, 0x40, 0xcb, 0xd5, 0x06, 0xba, 0x06, 0x8b, 0x41, 0x44,
	0x64, 0x3a, 0x9e, 0xde, 0xad, 0xa8, 0xdd, 0x96, 0x01, 0x25, 0x2b, 0x77, 0xfe, 0x00, 0xa8, 0xdd,
	0x0f, 0x82, 0xe2, 0xf8, 0x04, 0xc7, 0xc4, 0x90, 0xab, 0x35, 0xea, 0x42, 0xcd, 0xd7, 0x59, 0x1b,
	0xf2, 0xc2, 0x44, 0x77, 0xa1, 0x1e, 0x62, 0xee, 0xd1, 0x64, 0x9f, 0x29, 0xe6, 0xe6, 0xe6, 0x95,
	0xde, 0xd1, 0xfa, 0xf5, 0x0c, 0x71, 0x6f, 0x1b, 0x73, 0x99, 0xbf, 0x5b, 0x0b, 0xf5, 0x42, 0xc6,
	0x66, 0x38, 0xd6, 0xb1, 0xf3, 0xa7, 0xc7, 0xba, 0xf7, 0xbf, 0xd5, 0xb1, 0x19, 0x8e, 0x55, 0xec,
	0xd7, 0xd0, 0x4c, 0x49, 0x16, 0x53, 0xce, 0x65, 0x2f, 0xba, 0xd5, 0xb5, 0xca, 0x7a, 0x73, 0x73,
	0xfd, 0xa4, 0xf0, 0xdd, 0x89, 0xeb, 0xc3, 0x44, 0x64, 0x23, 0xb7, 0x1c, 0x8c, 0xee, 0xc1, 0x42,
	0x98, 0xb1, 0x3c, 0xe5, 0xdd, 0x05, 0x45, 0x73, 0xed, 0xc4, 0x2f, 0x50, 0x5e, 0x9a, 0xc1, 0x84,
	0xa0, 0x47, 0xb0, 0xb4, 0xaf, 0xda, 0xea, 0x99, 0x92, 0xf0, 0x6e, 0x4d, 0xb1, 0xac, 0x4e, 0xb3,
	0x1c, 0xe9, 0xbe, 0xdb, 0xde, 0x2f, 0x9b, 0x1c, 0x7d, 0x0e, 0x20, 0xfb, 0xa3, 0xaa, 0xc1, 0xbb,
	0x75, 0x45, 0xd1, 0x9d, 0xa6, 0x28, 0x34, 0xe0, 0x36, 0x0e, 0xcd, 0x8a, 0xdb, 0x5f, 0x02, 0xec,
	0x46, 0x64, 0x10, 0x6a, 0x71, 0x74, 0xa1, 0x96, 0x2a, 0x2b, 0x33, 0x0d, 0x2c, 0xcc, 0x92, 0xdc,
	0xe6, 0xca, 0x72, 0xb3, 0xff, 0xb2, 0xa0, 0x66, 0x5a, 0xa3, 0xc4, 0x92, 0x67, 0x19, 0x49, 0x84,
	0x27, 0x98, 0xc0, 0x91, 0x51, 0x66, 0xcb, 0x80, 0xcf, 0x25, 0x86, 0x6e, 0x42, 0x47, 0x64, 0x38,
	0xe1, 0xfb, 0x24, 0xc3, 0x7e, 0x44, 0xbc, 0x10, 0x17, 0x92, 0x5b, 0x2a, 0xe3, 0xdb, 0x98, 0xa3,
	0x55, 0x00, 0x7d, 0xbc, 0x72, 0xd2, 0xca, 0x6b, 0x68, 0x44, 0x6e, 0x5f, 0x87, 0x36, 0x4d, 0x82,
	0x8c, 0x60, 0x4e, 0x3c, 0x9e, 0x12, 0x32, 0x50, 0x32, 0xb0, 0xdc, 0xc5, 0x02, 0xdd, 0x93, 0xa0,
	0x14, 0x76, 0x44, 0x63, 0x2a, 0xba, 0x55, 0x2d, 0x6c, 0x65, 0xa0, 0x87, 0xd0, 0xd2, 0x4c, 0x03,
	0xad, 0x20, 0xdd, 0x3b, 0xe7, 0x44, 0x09, 0x8c, 0x6b, 0xe4, 0x36, 0x4d, 0x9c, 0x34, 0xec, 0x67,
	0x50, 0x33, 0xe2, 0x42, 0x2b, 0xd0, 0xc0, 0x87, 0x98, 0x46, 0x32, 0x7b, 0xf5, 0xe5, 0x15, 0x77,
	0x02, 0xc8, 0xb9, 0xc8, 0x39, 0x19, 0x14, 0x63, 0x29, 0xd7, 0x32, 0x33, 0x5d, 0xa7, 0x8a, 0x02,
	0xb5, 0x61, 0x27, 0x30, 0xbf, 0x23, 0x48, 0x8c, 0xda, 0x30, 0x47, 0x07, 0xa6, 0x0d, 0x73, 0x74,
	0x80, 0x2e, 0x43, 0x93, 0x72, 0xef, 0x80, 0x8c, 0xbc, 0x14, 0xd3, 0x4c, 0x11, 0xd5, 0xdd, 0x06,
	0xe5, 0x8f, 0xc9, 0x68, 0x17, 0x53, 0xd5, 0xa1, 0x37, 0x84, 0x86, 0x43, 0x61, 0xe8, 0x8c, 0x85,
	0x2e, 0x03, 0x4c, 0xe4, 0xaa, 0x4a, 0xd4, 0x70, 0x4b, 0x88, 0xfd, 0x14, 0xaa, 0x4a, 0x99, 0x33,
	0x47, 0x77, 0x13, 0xaa, 0x54, 0x90, 0x58, 0xb6, 0x48, 0xd6, 0x67, 0xe5, 0xa4, 0xfa, 0xc8, 0x8c,
	0x5d, 0xed, 0x6a, 0x7f, 0xb4, 0x00, 0x26, 0x23, 0x33, 0x93, 0xf6, 0x0a, 0x34, 0xd5, 0x00, 0x78,
	0xd2, 0xd2, 0xe4, 0x0d, 0x17, 0x14, 0xf4, 0x44, 0x22, 0x93, 0x73, 0x2b, 0x9f, 0x7c, 0xae, 0x6c,
	0x80, 0x18, 0x66, 0x84, 0x0f, 0x59, 0xa4, 0xa5, 0x50, 0x71, 0x27, 0x80, 0xed, 0x43, 0x67, 0x7a,
	0x8e, 0x51, 0x07, 0x2a, 0x07, 0x64, 0x64, 0x32, 0x93, 0x4b, 0x74, 0x07, 0xaa, 0x87, 0x38, 0xca,
	0xf5, 0x45, 0x75, 0x9a, 0x1e, 0xc6, 0x54, 0xae, 0x0e, 0xb8, 0x3b, 0x77, 0xc7, 0xb2, 0x5f, 0x40,
	0xb3, 0x34, 0xe4, 0x33, 0xe8, 0x6f, 0x1f, 0xa5, 0x5f, 0x3d, 0xf5, 0xaa, 0x28, 0x31, 0x3b, 0xbf,
	0x59, 0x13, 0xa1, 0x2d, 0x43, 0x5d, 0xca, 0xc7, 0xcb, 0x70, 0x6c, 0x74, 0x56, 0x93, 0xb6, 0x8b,
	0x63, 0x39, 0x81, 0x63, 0xc9, 0xa9, 0x7d, 0x2d, 0xb7, 0xd6, 0x18, 0x94, 0x4e, 0x97, 0xa0, 0xa1,
	0x94, 0xa6, 0x1c, 0xb4, 0x56, 0xea, 0x0a, 0x90, 0x9b, 0xab, 0x00, 0x9c, 0x44, 0x91, 0x97, 0x66,
	0x34, 0x20, 0x66, 0xa0, 0x1a, 0x12, 0xd9, 0x95, 0x80, 0x8c, 0xf5, 0xf3, 0x91, 0xd9, 0xd5, 0x03,
	0x55, 0xf7, 0xf3, 0x91, 0xda, 0x74, 0x7e, 0x80, 0xfa, 0x36, 0xe6, 0xae, 0x7c, 0xe0, 0xd0, 0x3a,
	0x74, 0x22, 0xf6, 0x86, 0x70, 0x21, 0x67, 0xd7, 0xcb, 0x24, 0x66, 0xae, 0x83, 0xb6, 0xc6, 0xcb,
	0x9e, 0x31, 0x19, 0x50, 0x9c, 0x94, 0x3c, 0xf5, 0x85, 0xd0, 0xd6, 0x78, 0xe1, 0xe9, 0x3c, 0x83,
	0xff, 0x6c, 0x13, 0x61, 0x6a, 0xe4, 0x92, 0xd7, 0x39, 0xe1, 0xb3, 0x1f, 0x9c, 0x75, 0xe8, 0xf8,
	0x23, 0x2f, 0x62, 0x49, 0x28, 0x13, 0x50, 0x35, 0x36, 0xf3, 0xd2, 0xf6, 0x47, 0xdf, 0x68, 0xf8,
	0x81, 0x44, 0x9d, 0x97, 0x80, 0xca, 0x94, 0x3c, 0x65, 0x09, 0x27, 0xe8, 0x16, 0x2c, 0xe8, 0xc7,
	0x57, 0xb1, 0x36, 0x37, 0x51, 0x4f, 0x3f, 0xc9, 0xaa, 0x47, 0x7b, 0x6a, 0xc7, 0x35, 0x1e, 0xf2,
	0xca, 0xc4, 0x3a, 0x5c, 0x1d, 0xd1, 0x70, 0x0b, 0xd3, 0x79, 0x05, 0x17, 0x26, 0xdc, 0x5b, 0xa3,
	0xdd, 0xdc, 0x2f, 0x72, 0xbe, 0x08, 0xb5, 0x34, 0xf7, 0xbd, 0x89, 0x38, 0x16, 0xd2, 0xdc, 0x7f,
	0x4c, 0x46, 0xff, 0x22, 0x71, 0x0c, 0x17, 0x8f, 0x91, 0x9f, 0x21, 0x7b, 0x1b, 0xea, 0x26, 0xdd,
	0x62, 0x0a, 0xc7, 0xb6, 0xf3, 0x02, 0x96, 0x8a, 0x87, 0xf3, 0x2c, 0xd4, 0xcb, 0xa5, 0xf7, 0xd9,
	0x54, 0xc6, 0x3c, 0xbf, 0xce, 0x2b, 0xe8, 0x14, 0x4d, 0x3d, 0x13, 0xf5, 0x25, 0x68, 0x68, 0xad,
	0x0c, 0x68, 0xc1, 0x2d, 0x7f, 0x47, 0xb8, 0xd2, 0x76, 0xde, 0xc3, 0xf2, 0x36, 0x11, 0x0f, 0x58,
	0x22, 0x32, 0x1c, 0x88, 0x3d, 0xc1, 0x32, 0x1c, 0x92, 0xa2, 0xf2, 0xd3, 0x97, 0xaa, 0x19, 0xd1,
	0xb9, 0xc9, 0x88, 0x9e, 0x87, 0xea, 0x3e, 0x25, 0xd1, 0x40, 0x4d, 0x46, 0xc3, 0xd5, 0xc6, 0xcc,
	0xc6, 0xcc, 0xcf, 0x6c, 0x4c, 0x08, 0x4b, 0x53, 0x67, 0x4b, 0x89, 0x0e, 0xb0, 0xc0, 0x85, 0x44,
	0xe5, 0x5a, 0xce, 0x99, 0x1f, 0xb1, 0xe0, 0xc0, 0x1b, 0x62, 0x3e, 0x34, 0xe7, 0x37, 0x14, 0xf2,
	0x15, 0xe6, 0x43, 0x74, 0x15, 0x5a, 0x7a, 0x3b, 0xc9, 0x63, 0x9f, 0x64, 0x66, 0x4c, 0x9b, 0x0a,
	0x7b, 0xa2, 0x20, 0x87, 0x83, 0x3d, 0xeb, 0x3b, 0xcf, 0x50, 0xce, 0x9b, 0xd0, 0x09, 0x0c, 0x8d,
	0xc7, 0x35, 0x8f, 0xc9, 0x68, 0x29, 0x38, 0x4a, 0xef, 0xb4, 0xa1, 0xf5, 0x30, 0x4e, 0xc5, 0xc8,
	0xd4, 0x73, 0xf3, 0x97, 0x2a, 0xfc, 0x77, 0x87, 0x99, 0x6f, 0x7f, 0x26, 0xef, 0xb1, 0x3d, 0x92,
	0x1d, 0xca, 0x9b, 0xe2, 0x83, 0x05, 0x30, 0x51, 0x28, 0xba, 0x3a, 0x7d, 0xd5, 0x1d, 0x9b, 0x64,
	0xdb, 0x39, 0xcd, 0x45, 0x7f, 0x96, 0xb3, 0xf1, 0xe1, 0xf7, 0x3f, 0x3f, 0xce, 0xdd, 0x40, 0xd7,
	0xfb, 0xe1, 0x78, 0xb3, 0xff, 0x4e, 0x0e, 0xfd, 0xfb, 0xfe, 0xbb, 0xe9, 0x0e, 0xbd, 0x47, 0xbf,
	0x5a, 0xb0, 0x34, 0x35, 0x26, 0xe8, 0x7f, 0x27, 0x1f, 0x53, 0x1e, 0x52, 0xfb, 0xc6, 0x3f, 0xfa,
	0x99, 0x9c, 0x3e, 0x53, 0x39, 0xf5, 0xd1, 0x46, 0x29, 0x27, 0xe5, 0xd1, 0x7f, 0x67, 0xa6, 0x7c,
	0x66, 0x6e, 0x3f, 0xaa, 0xfa, 0x8c, 0x7f, 0x3d, 0x4c, 0x9f, 0x56, 0x2e, 0xb3, 0x7d, 0xec, 0x97,
	0xed, 0xd4, 0x60, 0x3a, 0xe7, 0x54, 0x0e, 0x8b, 0xa8, 0x29, 0x73, 0x28, 0x38, 0x03, 0x68, 0x6e,
	0x93, 0xc9, 0x45, 0x7b, 0xfa, 0x11, 0x6b, 0xc7, 0x3e, 0x77, 0x6a, 0x42, 0x9d, 0xf3, 0xea, 0x8c,
	0x36, 0x6a, 0xc9, 0x33, 0xc6, 0xac, 0x3f, 0x5b, 0xea, 0x0a, 0x9d, 0xd6, 0xfc, 0xcd, 0x19, 0xd5,
	0x9b, 0x3d, 0x93, 0xf6, 0xad, 0x4f, 0x71, 0x35, 0x39, 0x5c, 0x56, 0x39, 0x74, 0x9d, 0x73, 0x32,
	0x87, 0x29, 0xa7, 0xbb, 0xd6, 0xad, 0x2d, 0x0a, 0xcb, 0x01, 0x8b, 0x7b, 0x3e, 0xf5, 0xd9, 0xdb,
	0xde, 0x80, 0xbc, 0xd5, 0xff, 0x9e, 0x7a, 0x8a, 0x7b, 0xab, 0xbd, 0xf3, 0x74, 0xef, 0xb9, 0x12,
	0xe9, 0xae, 0x44, 0x5f, 0x7e, 0x11, 0x52, 0x61, 0x5c, 0x03, 0x16, 0xf7, 0x7d, 0x1a, 0xfe, 0xbf,
	0xaf, 0xfc, 0x03, 0x36, 0x20, 0xbd, 0x90, 0x8a, 0x7e, 0xe9, 0x9f, 0xde, 0x46, 0xc8, 0xee, 0xa5,
	0xfe, 0x24, 0x53, 0x7f, 0x41, 0xb9, 0xde, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x6f, 0x3f,
	0x95, 0x0f, 0x0e, 0x00, 0x00,
}
