// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chain-query/query.proto

package pbchainquery // import "github.com/gisvr/protocode/chain-query-go"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import shared_go "github.com/gisvr/protocode/shared-go"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionDirection int32

const (
	TransactionDirection_Direction_Send    TransactionDirection = 0
	TransactionDirection_Direction_Receive TransactionDirection = 1
)

var TransactionDirection_name = map[int32]string{
	0: "Direction_Send",
	1: "Direction_Receive",
}
var TransactionDirection_value = map[string]int32{
	"Direction_Send":    0,
	"Direction_Receive": 1,
}

func (x TransactionDirection) String() string {
	return proto.EnumName(TransactionDirection_name, int32(x))
}
func (TransactionDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{0}
}

type TransactionsOrder int32

const (
	TransactionsOrder_Order_DESC TransactionsOrder = 0
	TransactionsOrder_Order_ASC  TransactionsOrder = 1
)

var TransactionsOrder_name = map[int32]string{
	0: "Order_DESC",
	1: "Order_ASC",
}
var TransactionsOrder_value = map[string]int32{
	"Order_DESC": 0,
	"Order_ASC":  1,
}

func (x TransactionsOrder) String() string {
	return proto.EnumName(TransactionsOrder_name, int32(x))
}
func (TransactionsOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{1}
}

// 表示交易里面的一个参与方
type Participant struct {
	Amount               float64          `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              []string         `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Token                *shared_go.Token `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{0}
}
func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (dst *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(dst, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Participant) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Participant) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// 表示单笔交易
type Transaction struct {
	Direction            TransactionDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=chainquery.api.TransactionDirection" json:"direction,omitempty"`
	Time                 int64                `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Amount               float64              `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	FromAddress          []string             `protobuf:"bytes,4,rep,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // Deprecated: Do not use.
	ToAddress            []string             `protobuf:"bytes,5,rep,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // Deprecated: Do not use.
	Sender               []*Participant       `protobuf:"bytes,6,rep,name=sender,proto3" json:"sender,omitempty"`
	Receiver             []*Participant       `protobuf:"bytes,7,rep,name=receiver,proto3" json:"receiver,omitempty"`
	TxId                 string               `protobuf:"bytes,8,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	BlockNum             int64                `protobuf:"varint,9,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	CoinLeft             float64              `protobuf:"fixed64,10,opt,name=coin_left,json=coinLeft,proto3" json:"coin_left,omitempty"`
	TransFee             float64              `protobuf:"fixed64,11,opt,name=trans_fee,json=transFee,proto3" json:"trans_fee,omitempty"`
	FeeToken             *shared_go.Token     `protobuf:"bytes,12,opt,name=fee_token,json=feeToken,proto3" json:"fee_token,omitempty"`
	Memo                 string               `protobuf:"bytes,13,opt,name=memo,proto3" json:"memo,omitempty"`
	Remark               string               `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`
	GlobalSequence       uint64               `protobuf:"varint,15,opt,name=global_sequence,json=globalSequence,proto3" json:"global_sequence,omitempty"`
	TxStatus             int32                `protobuf:"varint,16,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	Confirmations        int32                `protobuf:"varint,17,opt,name=Confirmations,proto3" json:"Confirmations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetDirection() TransactionDirection {
	if m != nil {
		return m.Direction
	}
	return TransactionDirection_Direction_Send
}

func (m *Transaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// Deprecated: Do not use.
func (m *Transaction) GetFromAddress() []string {
	if m != nil {
		return m.FromAddress
	}
	return nil
}

// Deprecated: Do not use.
func (m *Transaction) GetToAddress() []string {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *Transaction) GetSender() []*Participant {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Transaction) GetReceiver() []*Participant {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Transaction) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Transaction) GetBlockNum() int64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Transaction) GetCoinLeft() float64 {
	if m != nil {
		return m.CoinLeft
	}
	return 0
}

func (m *Transaction) GetTransFee() float64 {
	if m != nil {
		return m.TransFee
	}
	return 0
}

func (m *Transaction) GetFeeToken() *shared_go.Token {
	if m != nil {
		return m.FeeToken
	}
	return nil
}

func (m *Transaction) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Transaction) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Transaction) GetGlobalSequence() uint64 {
	if m != nil {
		return m.GlobalSequence
	}
	return 0
}

func (m *Transaction) GetTxStatus() int32 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

func (m *Transaction) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

type GetBalanceRequest struct {
	Token                *shared_go.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Address              string           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MinConfirms          int32            `protobuf:"varint,3,opt,name=min_confirms,json=minConfirms,proto3" json:"min_confirms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{2}
}
func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(dst, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetBalanceRequest) GetMinConfirms() int32 {
	if m != nil {
		return m.MinConfirms
	}
	return 0
}

type GetBalanceResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                *shared_go.Token  `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Address              string            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Balance              float64           `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{3}
}
func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(dst, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetBalanceResponse) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetBalanceResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetBalanceResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type ListTransactionRequest struct {
	Token                *shared_go.Token  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TxStart              uint32            `protobuf:"varint,4,opt,name=tx_start,json=txStart,proto3" json:"tx_start,omitempty"`
	TxCount              uint32            `protobuf:"varint,5,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxOrder              TransactionsOrder `protobuf:"varint,6,opt,name=tx_order,json=txOrder,proto3,enum=chainquery.api.TransactionsOrder" json:"tx_order,omitempty"`
	Memo                 string            `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListTransactionRequest) Reset()         { *m = ListTransactionRequest{} }
func (m *ListTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ListTransactionRequest) ProtoMessage()    {}
func (*ListTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{4}
}
func (m *ListTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransactionRequest.Unmarshal(m, b)
}
func (m *ListTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *ListTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransactionRequest.Merge(dst, src)
}
func (m *ListTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ListTransactionRequest.Size(m)
}
func (m *ListTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransactionRequest proto.InternalMessageInfo

func (m *ListTransactionRequest) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ListTransactionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ListTransactionRequest) GetTxStart() uint32 {
	if m != nil {
		return m.TxStart
	}
	return 0
}

func (m *ListTransactionRequest) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *ListTransactionRequest) GetTxOrder() TransactionsOrder {
	if m != nil {
		return m.TxOrder
	}
	return TransactionsOrder_Order_DESC
}

func (m *ListTransactionRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type ListTransactionResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                *shared_go.Token  `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Address              string            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Transactions         []*Transaction    `protobuf:"bytes,4,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListTransactionResponse) Reset()         { *m = ListTransactionResponse{} }
func (m *ListTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*ListTransactionResponse) ProtoMessage()    {}
func (*ListTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{5}
}
func (m *ListTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransactionResponse.Unmarshal(m, b)
}
func (m *ListTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *ListTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransactionResponse.Merge(dst, src)
}
func (m *ListTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_ListTransactionResponse.Size(m)
}
func (m *ListTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransactionResponse proto.InternalMessageInfo

func (m *ListTransactionResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListTransactionResponse) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ListTransactionResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ListTransactionResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ListUnspentRequest struct {
	Token                *shared_go.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Address              string           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListUnspentRequest) Reset()         { *m = ListUnspentRequest{} }
func (m *ListUnspentRequest) String() string { return proto.CompactTextString(m) }
func (*ListUnspentRequest) ProtoMessage()    {}
func (*ListUnspentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{6}
}
func (m *ListUnspentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentRequest.Unmarshal(m, b)
}
func (m *ListUnspentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentRequest.Marshal(b, m, deterministic)
}
func (dst *ListUnspentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentRequest.Merge(dst, src)
}
func (m *ListUnspentRequest) XXX_Size() int {
	return xxx_messageInfo_ListUnspentRequest.Size(m)
}
func (m *ListUnspentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentRequest proto.InternalMessageInfo

func (m *ListUnspentRequest) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ListUnspentRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Unspent struct {
	TxId                 string           `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Vout                 uint32           `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	ScriptPubkey         string           `protobuf:"bytes,3,opt,name=script_pubkey,json=scriptPubkey,proto3" json:"script_pubkey,omitempty"`
	Amount               float64          `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Blockhash            string           `protobuf:"bytes,5,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Confirmations        int32            `protobuf:"varint,6,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Token                *shared_go.Token `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Unspent) Reset()         { *m = Unspent{} }
func (m *Unspent) String() string { return proto.CompactTextString(m) }
func (*Unspent) ProtoMessage()    {}
func (*Unspent) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{7}
}
func (m *Unspent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unspent.Unmarshal(m, b)
}
func (m *Unspent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unspent.Marshal(b, m, deterministic)
}
func (dst *Unspent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unspent.Merge(dst, src)
}
func (m *Unspent) XXX_Size() int {
	return xxx_messageInfo_Unspent.Size(m)
}
func (m *Unspent) XXX_DiscardUnknown() {
	xxx_messageInfo_Unspent.DiscardUnknown(m)
}

var xxx_messageInfo_Unspent proto.InternalMessageInfo

func (m *Unspent) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Unspent) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *Unspent) GetScriptPubkey() string {
	if m != nil {
		return m.ScriptPubkey
	}
	return ""
}

func (m *Unspent) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Unspent) GetBlockhash() string {
	if m != nil {
		return m.Blockhash
	}
	return ""
}

func (m *Unspent) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Unspent) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ListUnspentResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                *shared_go.Token  `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Address              string            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Unspents             []*Unspent        `protobuf:"bytes,4,rep,name=unspents,proto3" json:"unspents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListUnspentResponse) Reset()         { *m = ListUnspentResponse{} }
func (m *ListUnspentResponse) String() string { return proto.CompactTextString(m) }
func (*ListUnspentResponse) ProtoMessage()    {}
func (*ListUnspentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{8}
}
func (m *ListUnspentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentResponse.Unmarshal(m, b)
}
func (m *ListUnspentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentResponse.Marshal(b, m, deterministic)
}
func (dst *ListUnspentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentResponse.Merge(dst, src)
}
func (m *ListUnspentResponse) XXX_Size() int {
	return xxx_messageInfo_ListUnspentResponse.Size(m)
}
func (m *ListUnspentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentResponse proto.InternalMessageInfo

func (m *ListUnspentResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListUnspentResponse) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ListUnspentResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ListUnspentResponse) GetUnspents() []*Unspent {
	if m != nil {
		return m.Unspents
	}
	return nil
}

type QueryTransactionRequest struct {
	Token                *shared_go.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TxId                 string           `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Address              string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryTransactionRequest) Reset()         { *m = QueryTransactionRequest{} }
func (m *QueryTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTransactionRequest) ProtoMessage()    {}
func (*QueryTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{9}
}
func (m *QueryTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTransactionRequest.Unmarshal(m, b)
}
func (m *QueryTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *QueryTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTransactionRequest.Merge(dst, src)
}
func (m *QueryTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTransactionRequest.Size(m)
}
func (m *QueryTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTransactionRequest proto.InternalMessageInfo

func (m *QueryTransactionRequest) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *QueryTransactionRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *QueryTransactionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryTransactionResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Transaction          *Transaction      `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryTransactionResponse) Reset()         { *m = QueryTransactionResponse{} }
func (m *QueryTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTransactionResponse) ProtoMessage()    {}
func (*QueryTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{10}
}
func (m *QueryTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTransactionResponse.Unmarshal(m, b)
}
func (m *QueryTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTransactionResponse.Marshal(b, m, deterministic)
}
func (dst *QueryTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTransactionResponse.Merge(dst, src)
}
func (m *QueryTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTransactionResponse.Size(m)
}
func (m *QueryTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTransactionResponse proto.InternalMessageInfo

func (m *QueryTransactionResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryTransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TokenInfo struct {
	Token                *shared_go.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Balance              string           `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{11}
}
func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (dst *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(dst, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetToken() *shared_go.Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TokenInfo) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// 一次请求不能查两种主链的代币
type GetTokensBalanceRequest struct {
	Chain                string             `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address              string             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Tokens               []*shared_go.Token `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTokensBalanceRequest) Reset()         { *m = GetTokensBalanceRequest{} }
func (m *GetTokensBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokensBalanceRequest) ProtoMessage()    {}
func (*GetTokensBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{12}
}
func (m *GetTokensBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokensBalanceRequest.Unmarshal(m, b)
}
func (m *GetTokensBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokensBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokensBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokensBalanceRequest.Merge(dst, src)
}
func (m *GetTokensBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokensBalanceRequest.Size(m)
}
func (m *GetTokensBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokensBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokensBalanceRequest proto.InternalMessageInfo

func (m *GetTokensBalanceRequest) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *GetTokensBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetTokensBalanceRequest) GetTokens() []*shared_go.Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type GetTokensBalanceResponse struct {
	Status               *shared_go.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tokeninfos           []*TokenInfo      `protobuf:"bytes,2,rep,name=tokeninfos,proto3" json:"tokeninfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetTokensBalanceResponse) Reset()         { *m = GetTokensBalanceResponse{} }
func (m *GetTokensBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokensBalanceResponse) ProtoMessage()    {}
func (*GetTokensBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_e407a6a2ae273458, []int{13}
}
func (m *GetTokensBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokensBalanceResponse.Unmarshal(m, b)
}
func (m *GetTokensBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokensBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *GetTokensBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokensBalanceResponse.Merge(dst, src)
}
func (m *GetTokensBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokensBalanceResponse.Size(m)
}
func (m *GetTokensBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokensBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokensBalanceResponse proto.InternalMessageInfo

func (m *GetTokensBalanceResponse) GetStatus() *shared_go.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetTokensBalanceResponse) GetTokeninfos() []*TokenInfo {
	if m != nil {
		return m.Tokeninfos
	}
	return nil
}

func init() {
	proto.RegisterType((*Participant)(nil), "chainquery.api.Participant")
	proto.RegisterType((*Transaction)(nil), "chainquery.api.Transaction")
	proto.RegisterType((*GetBalanceRequest)(nil), "chainquery.api.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "chainquery.api.GetBalanceResponse")
	proto.RegisterType((*ListTransactionRequest)(nil), "chainquery.api.ListTransactionRequest")
	proto.RegisterType((*ListTransactionResponse)(nil), "chainquery.api.ListTransactionResponse")
	proto.RegisterType((*ListUnspentRequest)(nil), "chainquery.api.ListUnspentRequest")
	proto.RegisterType((*Unspent)(nil), "chainquery.api.Unspent")
	proto.RegisterType((*ListUnspentResponse)(nil), "chainquery.api.ListUnspentResponse")
	proto.RegisterType((*QueryTransactionRequest)(nil), "chainquery.api.QueryTransactionRequest")
	proto.RegisterType((*QueryTransactionResponse)(nil), "chainquery.api.QueryTransactionResponse")
	proto.RegisterType((*TokenInfo)(nil), "chainquery.api.TokenInfo")
	proto.RegisterType((*GetTokensBalanceRequest)(nil), "chainquery.api.GetTokensBalanceRequest")
	proto.RegisterType((*GetTokensBalanceResponse)(nil), "chainquery.api.GetTokensBalanceResponse")
	proto.RegisterEnum("chainquery.api.TransactionDirection", TransactionDirection_name, TransactionDirection_value)
	proto.RegisterEnum("chainquery.api.TransactionsOrder", TransactionsOrder_name, TransactionsOrder_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChainQueryServiceClient is the client API for ChainQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainQueryServiceClient interface {
	// 获取钱包余额
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// 获取钱包全部未花费的UTXO
	ListUnspent(ctx context.Context, in *ListUnspentRequest, opts ...grpc.CallOption) (*ListUnspentResponse, error)
	// 获取钱包全部的交易
	ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error)
	// 查询交易
	QueryTransaction(ctx context.Context, in *QueryTransactionRequest, opts ...grpc.CallOption) (*QueryTransactionResponse, error)
	// 查询钱包拥有的代币种类及数量
	GetTokensBalance(ctx context.Context, in *GetTokensBalanceRequest, opts ...grpc.CallOption) (*GetTokensBalanceResponse, error)
}

type chainQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewChainQueryServiceClient(cc *grpc.ClientConn) ChainQueryServiceClient {
	return &chainQueryServiceClient{cc}
}

func (c *chainQueryServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.ChainQueryService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainQueryServiceClient) ListUnspent(ctx context.Context, in *ListUnspentRequest, opts ...grpc.CallOption) (*ListUnspentResponse, error) {
	out := new(ListUnspentResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.ChainQueryService/ListUnspent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainQueryServiceClient) ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error) {
	out := new(ListTransactionResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.ChainQueryService/ListTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainQueryServiceClient) QueryTransaction(ctx context.Context, in *QueryTransactionRequest, opts ...grpc.CallOption) (*QueryTransactionResponse, error) {
	out := new(QueryTransactionResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.ChainQueryService/QueryTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainQueryServiceClient) GetTokensBalance(ctx context.Context, in *GetTokensBalanceRequest, opts ...grpc.CallOption) (*GetTokensBalanceResponse, error) {
	out := new(GetTokensBalanceResponse)
	err := c.cc.Invoke(ctx, "/chainquery.api.ChainQueryService/GetTokensBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainQueryServiceServer is the server API for ChainQueryService service.
type ChainQueryServiceServer interface {
	// 获取钱包余额
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// 获取钱包全部未花费的UTXO
	ListUnspent(context.Context, *ListUnspentRequest) (*ListUnspentResponse, error)
	// 获取钱包全部的交易
	ListTransaction(context.Context, *ListTransactionRequest) (*ListTransactionResponse, error)
	// 查询交易
	QueryTransaction(context.Context, *QueryTransactionRequest) (*QueryTransactionResponse, error)
	// 查询钱包拥有的代币种类及数量
	GetTokensBalance(context.Context, *GetTokensBalanceRequest) (*GetTokensBalanceResponse, error)
}

func RegisterChainQueryServiceServer(s *grpc.Server, srv ChainQueryServiceServer) {
	s.RegisterService(&_ChainQueryService_serviceDesc, srv)
}

func _ChainQueryService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.ChainQueryService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainQueryService_ListUnspent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnspentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServiceServer).ListUnspent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.ChainQueryService/ListUnspent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServiceServer).ListUnspent(ctx, req.(*ListUnspentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainQueryService_ListTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServiceServer).ListTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.ChainQueryService/ListTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServiceServer).ListTransaction(ctx, req.(*ListTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainQueryService_QueryTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServiceServer).QueryTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.ChainQueryService/QueryTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServiceServer).QueryTransaction(ctx, req.(*QueryTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainQueryService_GetTokensBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokensBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServiceServer).GetTokensBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainquery.api.ChainQueryService/GetTokensBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServiceServer).GetTokensBalance(ctx, req.(*GetTokensBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainquery.api.ChainQueryService",
	HandlerType: (*ChainQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _ChainQueryService_GetBalance_Handler,
		},
		{
			MethodName: "ListUnspent",
			Handler:    _ChainQueryService_ListUnspent_Handler,
		},
		{
			MethodName: "ListTransaction",
			Handler:    _ChainQueryService_ListTransaction_Handler,
		},
		{
			MethodName: "QueryTransaction",
			Handler:    _ChainQueryService_QueryTransaction_Handler,
		},
		{
			MethodName: "GetTokensBalance",
			Handler:    _ChainQueryService_GetTokensBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chain-query/query.proto",
}

func init() { proto.RegisterFile("chain-query/query.proto", fileDescriptor_query_e407a6a2ae273458) }

var fileDescriptor_query_e407a6a2ae273458 = []byte{
	// 1183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xef, 0xf8, 0xdb, 0xc7, 0xb1, 0x6b, 0x8f, 0xfb, 0x6f, 0x36, 0x6e, 0xf5, 0xc7, 0xdd, 0x16,
	0x6a, 0x22, 0xd5, 0x16, 0x2e, 0x12, 0xa2, 0x14, 0xa1, 0x24, 0x85, 0xaa, 0x52, 0x55, 0xc2, 0xba,
	0x08, 0x89, 0x9b, 0xd5, 0x7a, 0x3d, 0x76, 0x56, 0xf6, 0xce, 0x38, 0xbb, 0xe3, 0xc8, 0xb9, 0xa4,
	0x12, 0xf0, 0x00, 0x5c, 0xf3, 0x20, 0x3c, 0x02, 0xd7, 0xdc, 0x72, 0x07, 0x37, 0xbc, 0x05, 0x9a,
	0x8f, 0xf5, 0xae, 0xbd, 0x89, 0x03, 0xa5, 0x52, 0x6f, 0xac, 0x99, 0x73, 0x7e, 0x33, 0xe7, 0x77,
	0x3e, 0x67, 0x0d, 0xbb, 0xee, 0x89, 0xe3, 0xd1, 0x07, 0xa7, 0x0b, 0x12, 0x9c, 0xf7, 0xe4, 0x6f,
	0x77, 0x1e, 0x30, 0xce, 0x70, 0x4d, 0x2a, 0x94, 0xc4, 0x99, 0x7b, 0xad, 0xdb, 0x13, 0xc6, 0x26,
	0x33, 0xd2, 0x73, 0xe6, 0x5e, 0xcf, 0xa1, 0x94, 0x71, 0x87, 0x7b, 0x8c, 0x86, 0x0a, 0xdd, 0xc2,
	0xe1, 0x89, 0x13, 0x90, 0x51, 0x8f, 0xb3, 0x29, 0xa1, 0x5a, 0xd6, 0xd4, 0xb2, 0x90, 0x3b, 0x7c,
	0xa1, 0x81, 0xe6, 0x09, 0x54, 0x8e, 0x9d, 0x80, 0x7b, 0xae, 0x37, 0x77, 0x28, 0xc7, 0x37, 0xa1,
	0xe0, 0xf8, 0x6c, 0x41, 0xb9, 0x81, 0xda, 0xa8, 0x83, 0x2c, 0xbd, 0xc3, 0x06, 0x14, 0x9d, 0xd1,
	0x28, 0x20, 0x61, 0x68, 0x64, 0xda, 0xd9, 0x4e, 0xd9, 0x8a, 0xb6, 0xf8, 0x3e, 0xe4, 0xa5, 0x11,
	0x23, 0xdb, 0x46, 0x9d, 0x4a, 0xbf, 0xd1, 0x55, 0x56, 0x04, 0xc7, 0xee, 0x4b, 0xa1, 0xb0, 0x94,
	0xde, 0xfc, 0x2b, 0x07, 0x95, 0x97, 0x81, 0x43, 0x43, 0xc7, 0x15, 0x4c, 0xf1, 0x21, 0x94, 0x47,
	0x5e, 0x40, 0xe4, 0x46, 0x5a, 0xab, 0xf5, 0xef, 0x75, 0xd7, 0x9d, 0xec, 0x26, 0xf0, 0x4f, 0x22,
	0xac, 0x15, 0x1f, 0xc3, 0x18, 0x72, 0xdc, 0xf3, 0x89, 0x91, 0x69, 0xa3, 0x4e, 0xd6, 0x92, 0xeb,
	0x84, 0x0b, 0xd9, 0x35, 0x17, 0xde, 0x85, 0x9d, 0x71, 0xc0, 0x7c, 0x3b, 0xf2, 0x23, 0x27, 0xfc,
	0x38, 0xcc, 0x18, 0xc8, 0xaa, 0x08, 0xf9, 0x81, 0xf6, 0xe7, 0x0e, 0x00, 0x67, 0x2b, 0x50, 0x7e,
	0x05, 0x2a, 0x73, 0x16, 0x41, 0x1e, 0x42, 0x21, 0x24, 0x74, 0x44, 0x02, 0xa3, 0xd0, 0xce, 0x76,
	0x2a, 0xfd, 0x5b, 0x9b, 0xb4, 0x13, 0x11, 0xb5, 0x34, 0x14, 0x7f, 0x04, 0xa5, 0x80, 0xb8, 0xc4,
	0x3b, 0x23, 0x81, 0x51, 0xbc, 0xfa, 0xd8, 0x0a, 0x8c, 0x9b, 0x90, 0xe7, 0x4b, 0xdb, 0x1b, 0x19,
	0xa5, 0x36, 0xea, 0x94, 0xad, 0x1c, 0x5f, 0x3e, 0x1b, 0xe1, 0x5b, 0x50, 0x1e, 0xce, 0x98, 0x3b,
	0xb5, 0xe9, 0xc2, 0x37, 0xca, 0xd2, 0xfb, 0x92, 0x14, 0xbc, 0x58, 0xf8, 0x42, 0xe9, 0x32, 0x8f,
	0xda, 0x33, 0x32, 0xe6, 0x06, 0xc8, 0x20, 0x94, 0x84, 0xe0, 0x39, 0x19, 0x73, 0xa1, 0xe4, 0x22,
	0xaa, 0xf6, 0x98, 0x10, 0xa3, 0xa2, 0x94, 0x52, 0xf0, 0x05, 0x21, 0xb8, 0x0b, 0xe5, 0x31, 0x21,
	0xb6, 0x4a, 0xe8, 0xce, 0x65, 0x09, 0x2d, 0x8d, 0x09, 0x91, 0x2b, 0x11, 0x7f, 0x9f, 0xf8, 0xcc,
	0xa8, 0x2a, 0x6a, 0x62, 0x2d, 0xe2, 0x1f, 0x10, 0xdf, 0x09, 0xa6, 0x46, 0x4d, 0x4a, 0xf5, 0x0e,
	0xdf, 0x87, 0xeb, 0x93, 0x19, 0x1b, 0x3a, 0x33, 0x3b, 0x24, 0xa7, 0x0b, 0x42, 0x5d, 0x62, 0x5c,
	0x6f, 0xa3, 0x4e, 0xce, 0xaa, 0x29, 0xf1, 0x40, 0x4b, 0x25, 0xc3, 0xa5, 0xad, 0xaa, 0xd4, 0xa8,
	0xb7, 0x51, 0x27, 0x6f, 0x95, 0xf8, 0x72, 0x20, 0xf7, 0xf8, 0x1e, 0x54, 0x8f, 0x18, 0x1d, 0x7b,
	0x81, 0xaf, 0xea, 0xdd, 0x68, 0x48, 0xc0, 0xba, 0xd0, 0x3c, 0x87, 0xc6, 0x53, 0xc2, 0x0f, 0x9d,
	0x99, 0x43, 0x5d, 0x62, 0x89, 0x8b, 0x43, 0x1e, 0x57, 0x2a, 0xda, 0x5e, 0xa9, 0xeb, 0xc5, 0x8e,
	0x92, 0xc5, 0x7e, 0x07, 0x76, 0x7c, 0x8f, 0xda, 0xae, 0x32, 0x16, 0xca, 0x0a, 0xcb, 0x5b, 0x15,
	0xdf, 0xa3, 0xda, 0x7e, 0x68, 0xfe, 0x8c, 0x00, 0x27, 0x6d, 0x87, 0x73, 0x46, 0x43, 0x82, 0xf7,
	0xa1, 0xa0, 0x3d, 0x52, 0xd6, 0x71, 0xd2, 0xba, 0xf2, 0xcd, 0xd2, 0x88, 0x98, 0x68, 0xe6, 0x9f,
	0x13, 0xcd, 0xae, 0x13, 0x35, 0xa0, 0x38, 0x54, 0x0c, 0x8c, 0x9c, 0xcc, 0x71, 0xb4, 0x35, 0xff,
	0x40, 0x70, 0xf3, 0xb9, 0x17, 0xf2, 0x44, 0x6b, 0xbd, 0xc1, 0x00, 0xed, 0x41, 0x49, 0xe5, 0x2e,
	0xe0, 0xd2, 0x70, 0xd5, 0x2a, 0xca, 0xd4, 0x05, 0x5c, 0xab, 0x5c, 0xd9, 0x99, 0xf9, 0x48, 0x75,
	0x24, 0x5b, 0xf3, 0xb1, 0x54, 0xb1, 0x40, 0xb5, 0x94, 0x98, 0x04, 0x77, 0xb6, 0x4c, 0x82, 0xf0,
	0x4b, 0x01, 0x14, 0xa7, 0xe5, 0x62, 0x55, 0x84, 0xc5, 0xb8, 0x08, 0xcd, 0x5f, 0x11, 0xec, 0xa6,
	0xbc, 0x7c, 0x3b, 0xa9, 0xf8, 0x0c, 0x76, 0x92, 0xe4, 0xe5, 0xdc, 0xb9, 0xa0, 0xf9, 0x93, 0x4c,
	0xd7, 0x0e, 0x98, 0xdf, 0x00, 0x16, 0xae, 0x7c, 0x4d, 0xc3, 0x39, 0xa1, 0xfc, 0xcd, 0x25, 0xcb,
	0xfc, 0x1d, 0x41, 0x51, 0xdf, 0x1a, 0x4f, 0x19, 0x94, 0x98, 0x32, 0x18, 0x72, 0x67, 0x6c, 0xc1,
	0xe5, 0xb9, 0xaa, 0x25, 0xd7, 0xf8, 0x2e, 0x54, 0x43, 0x37, 0xf0, 0xe6, 0xdc, 0x9e, 0x2f, 0x86,
	0x53, 0x72, 0xae, 0xdd, 0xdd, 0x51, 0xc2, 0x63, 0x29, 0x4b, 0xcc, 0xe0, 0xdc, 0xda, 0x0c, 0xbe,
	0xad, 0xc7, 0xd6, 0x89, 0x13, 0x9e, 0xc8, 0x22, 0x28, 0x5b, 0xb1, 0x40, 0xf4, 0xb6, 0xbb, 0xd6,
	0xdb, 0x05, 0xd5, 0xdb, 0x6b, 0xc2, 0xd8, 0xf1, 0xe2, 0x15, 0x0f, 0xce, 0x2f, 0x08, 0x9a, 0x6b,
	0x81, 0x7b, 0x3b, 0xf9, 0x7f, 0x08, 0xa5, 0x85, 0x62, 0x10, 0xe5, 0x7e, 0x77, 0x33, 0xf7, 0x11,
	0xc3, 0x15, 0xd0, 0x3c, 0x85, 0xdd, 0xaf, 0x84, 0xfa, 0xbf, 0x74, 0xe9, 0x2a, 0xa5, 0x99, 0x44,
	0x4a, 0x2f, 0xe5, 0x69, 0x7e, 0x8f, 0xc0, 0x48, 0xdb, 0x7c, 0x8d, 0x98, 0x7d, 0x0a, 0x15, 0x1e,
	0x5f, 0xa1, 0x23, 0xb7, 0xb5, 0xde, 0x93, 0x78, 0xf3, 0x05, 0x94, 0xa5, 0x1b, 0xcf, 0xe8, 0x98,
	0xfd, 0xab, 0x2a, 0x8f, 0x06, 0x9e, 0xae, 0xf2, 0x68, 0xe0, 0x71, 0xd8, 0x7d, 0x4a, 0xb8, 0x04,
	0x87, 0x1b, 0x2f, 0xc2, 0x0d, 0xc8, 0x4b, 0x56, 0xba, 0xe8, 0xd5, 0x66, 0xcb, 0x74, 0x7b, 0x1f,
	0x0a, 0xd2, 0x9a, 0x88, 0x5d, 0xf6, 0x62, 0x3a, 0x1a, 0x60, 0x7e, 0x87, 0xc0, 0x48, 0x9b, 0x7d,
	0x8d, 0x68, 0x7e, 0x2c, 0xbe, 0x47, 0xa6, 0x84, 0x7a, 0x74, 0xcc, 0xd4, 0xc7, 0x57, 0xa5, 0xbf,
	0x97, 0x0a, 0x66, 0x14, 0x30, 0x2b, 0x01, 0xde, 0x3f, 0x80, 0x1b, 0x17, 0x7d, 0x40, 0x61, 0x0c,
	0xb5, 0xd5, 0xc6, 0x1e, 0x10, 0x3a, 0xaa, 0x5f, 0xc3, 0xff, 0x83, 0x46, 0x2c, 0xb3, 0xd4, 0xb7,
	0x47, 0x1d, 0xed, 0xf7, 0xa1, 0x91, 0x9a, 0xbc, 0xb8, 0x06, 0x20, 0x17, 0xf6, 0x93, 0xcf, 0x07,
	0x47, 0xf5, 0x6b, 0xb8, 0x0a, 0x65, 0xb5, 0x3f, 0x18, 0x1c, 0xd5, 0x51, 0xff, 0xc7, 0x3c, 0x34,
	0x8e, 0x04, 0x3f, 0x59, 0x4d, 0x03, 0x12, 0x9c, 0x79, 0x2e, 0xc1, 0x14, 0x20, 0x7e, 0x16, 0x71,
	0x6a, 0xbe, 0xa7, 0x9e, 0xeb, 0x96, 0xb9, 0x0d, 0xa2, 0x02, 0x69, 0xee, 0xbd, 0xfa, 0xed, 0xcf,
	0x9f, 0x32, 0x4d, 0xb3, 0xd6, 0x3b, 0xfb, 0xa0, 0x17, 0xeb, 0x1f, 0xa1, 0x7d, 0x3c, 0x85, 0x4a,
	0xa2, 0xf9, 0x71, 0xea, 0xb6, 0xf4, 0x48, 0x6d, 0xdd, 0xdd, 0x8a, 0xd1, 0x26, 0x9b, 0xd2, 0x64,
	0x15, 0x57, 0x84, 0x49, 0xdd, 0xaf, 0xf8, 0x15, 0x82, 0xeb, 0x1b, 0xcf, 0x0d, 0x7e, 0xef, 0xa2,
	0xdb, 0xd2, 0xfd, 0xdc, 0xba, 0x7f, 0x25, 0x4e, 0x5b, 0xfe, 0xbf, 0xb4, 0x6c, 0x98, 0x4d, 0x61,
	0x79, 0x03, 0x24, 0x3c, 0xfe, 0x01, 0x41, 0x7d, 0xb3, 0x81, 0x71, 0xea, 0xf6, 0x4b, 0xc6, 0x4a,
	0xab, 0x73, 0x35, 0x50, 0xf3, 0x78, 0x47, 0xf2, 0xd8, 0x33, 0x6f, 0x08, 0x1e, 0x9b, 0xa8, 0x88,
	0xc8, 0x66, 0xed, 0xa7, 0x89, 0x5c, 0xd2, 0x94, 0x69, 0x22, 0x97, 0xb5, 0xd1, 0x3a, 0x91, 0x4d,
	0xd4, 0x23, 0xb4, 0x7f, 0x48, 0x60, 0xcf, 0x65, 0x7e, 0x77, 0xe8, 0x0d, 0xd9, 0xb2, 0x3b, 0x22,
	0x4b, 0xf5, 0x9f, 0xa7, 0x2b, 0xaf, 0x3e, 0x04, 0x49, 0xfd, 0x58, 0x48, 0xbe, 0x7d, 0x3c, 0xf1,
	0xb8, 0x86, 0xb9, 0xcc, 0xef, 0x0d, 0xbd, 0xc9, 0x87, 0x3d, 0x89, 0x75, 0xd9, 0x88, 0x74, 0x27,
	0x1e, 0xef, 0x25, 0xfe, 0x96, 0x3d, 0x98, 0xb0, 0x4f, 0xe6, 0xc3, 0x98, 0xe4, 0xb0, 0x20, 0xa1,
	0x0f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x07, 0x31, 0x5c, 0x5e, 0xbc, 0x0d, 0x00, 0x00,
}
